import type { LearningModeId } from "./types";

export type SubtitleTrack = "off" | "narragansett" | "english" | "both";
/** Spoken track during scene play — Narragansett is always the default. */
export type VoiceTrack = "narragansett" | "english" | "both" | "off";
export type VideoStyle = "cinematic" | "cartoon";
export type SceneSensitivity = "everyday" | "careful" | "sensitive";
export type MediaStatus = "ready" | "awaiting_upload";
/** learn = line-paced with TTS (default); watch = continuous video timeline */
export type PlayMode = "learn" | "watch";

export type SceneLine = {
  id: string;
  /** Prefer Host / Guest / Both (Friend allowed for little-ones cartoon scenes). */
  speaker: string;
  narragansett: string;
  english: string;
  startSec: number;
  endSec: number;
  /** Optional link into demo Williams lexicon word id */
  wordId?: string;
  /**
   * Packaged oral audio (language-first). Path under public/.
   * When set, player plays this before live TTS / browser speech.
   */
  audioSrc?: string;
};

/**
 * Optional window into a longer master film (Film V5 Full Day acts).
 * When set, ScenePlayer seeks/plays only [startSec, endSec) of videoSrc.
 */
export type MediaWindow = {
  startSec: number;
  endSec: number;
};

export type LearningScene = {
  id: string;
  title: string;
  summary: string;
  chapter: string;
  chapterNum: number;
  domain: string;
  sensitivity: SceneSensitivity;
  style: VideoStyle;
  modesAllowed: LearningModeId[];
  /** Default packaged reconstruction */
  videoSrc: string;
  posterSrc: string;
  /** Optional community/custom file: /scenes/uploads/{id}.mp4 */
  uploadSrc: string;
  /**
   * Learn-mode practice window (seconds). May exceed packaged clip length;
   * Watch mode uses real media duration from the video element.
   */
  durationSec: number;
  lines: SceneLine[];
  reconstructionNote: string;
  tags: string[];
  series?: string;
  mediaStatus?: MediaStatus;
  /** Suggested learning order within a mode (lower first) */
  pathOrder?: number;
  /**
   * When set, videoSrc is a longer master film and this scene plays only
   * the [startSec, endSec) window (Film V5 Full Day acts).
   */
  mediaWindow?: MediaWindow;
};

const note =
  "AI visual reconstruction for language learning. Dialogue forms from Williams 1643 (modern English). Not a living speaker recording. Audio for the language is synthesized for practice until living speaker recordings replace it. Drop your own video anytime via public/scenes/uploads — see docs/SCENES_UPLOAD.md.";

function scene(
  partial: Omit<LearningScene, "uploadSrc" | "reconstructionNote"> & {
    reconstructionNote?: string;
  },
): LearningScene {
  return {
    reconstructionNote: partial.reconstructionNote ?? note,
    uploadSrc: `/scenes/uploads/${partial.id}.mp4`,
    mediaStatus: partial.mediaStatus ?? "ready",
    ...partial,
  };
}

/** Space lines evenly across a target duration (for learn + watch pacing). */
function timed(
  lines: Omit<SceneLine, "startSec" | "endSec">[],
  totalSec: number,
): SceneLine[] {
  const n = lines.length;
  if (n === 0) return [];
  const slot = totalSec / n;
  return lines.map((l, i) => ({
    ...l,
    startSec: Math.round(i * slot * 100) / 100,
    endSec: Math.round(Math.min(totalSec, (i + 1) * slot) * 100) / 100,
  }));
}

/**
 * Historical demo scenes — expand anytime; drop matching uploads/{id}.mp4 to override video.
 * Forms stay Williams 1643 with modern English glosses; living Keepers replace later.
 * Timings target ~24–36s of practice context (learn mode + longer multi-shot video where available).
 */
export const SCENES: LearningScene[] = [
  // ——— Salutation ———
  scene({
    id: "greeting-dawn",
    title: "Greeting at dawn",
    summary:
      "A respectful welcome outside the dwelling — morning greeting, well-being, and respects.",
    chapter: "Salutation",
    chapterNum: 1,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 10,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/greeting-dawn.mp4",
    posterSrc: "/scenes/greeting-dawn.jpg",
    durationSec: 28,
    tags: ["greeting", "welcome", "hospitality"],
    lines: timed(
      [
        { id: "g1", speaker: "Host", narragansett: "Ascowequassunnúmmis", english: "Good morning." },
        { id: "g2", speaker: "Guest", narragansett: "Askuttaaquompsín", english: "How are you?" },
        { id: "g3", speaker: "Host", narragansett: "Asnpaumpmaúntam", english: "I am very well." },
        { id: "g4", speaker: "Guest", narragansett: "Taubút paump maúntaman", english: "I am glad you are well." },
        { id: "g5", speaker: "Host", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "g6", speaker: "Guest", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "g7", speaker: "Host", narragansett: "Asco wequássin", english: "Good evening. (evening form of greeting)" },
        { id: "g8", speaker: "Guest", narragansett: "Taubotneanawáyean", english: "I thank you." },
      ],
      28,
    ),
  }),
  scene({
    id: "greeting-kids",
    title: "Hello, friend (kids)",
    summary: "One continuous hello — same two friends, a short spoken greeting, then they stay together.",
    chapter: "Salutation",
    chapterNum: 1,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 1,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/greeting-kids.mp4?v=oneshot1",
    posterSrc: "/scenes/greeting-kids.jpg?v=oneshot1",
    durationSec: 30,
    tags: ["kids", "hq", "greeting", "cinematic", "speak"],
    lines: [
      { id: "k1", speaker: "Friend", startSec: 1.5, endSec: 4.2, narragansett: "Ascowequassunnúmmis", english: "Good morning.", audioSrc: "/audio/kids/k1.mp3" },
      { id: "k2", speaker: "Friend", startSec: 4.2, endSec: 6.7, narragansett: "Askuttaaquompsín", english: "How are you?", audioSrc: "/audio/kids/k2.mp3" },
      { id: "k3", speaker: "Friend", startSec: 6.7, endSec: 9.1, narragansett: "Asnpaumpmaúntam", english: "I am very well.", audioSrc: "/audio/kids/k3.mp3" },
      { id: "k4", speaker: "Friend", startSec: 9.1, endSec: 11.5, narragansett: "Cowaúnckamish", english: "My respects to you.", audioSrc: "/audio/kids/k4.mp3" },
      { id: "k5", speaker: "Friend", startSec: 11.5, endSec: 16, narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/kids/k5.mp3" },
    ],
  }),

  // ——— Eating ———
  scene({
    id: "meal-share",
    title: "Stay and eat",
    summary: "Hospitality at the fire — thirst, water, and sharing food.",
    chapter: "Eating and Entertainment",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 20,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/meal-share.mp4",
    posterSrc: "/scenes/meal-share.jpg",
    durationSec: 28,
    tags: ["food", "hospitality"],
    lines: timed(
      [
        { id: "m1", speaker: "Guest", narragansett: "Niccàwkatone", english: "I am thirsty." },
        { id: "m2", speaker: "Host", narragansett: "Nip, or nipéwese", english: "Some water." },
        { id: "m3", speaker: "Host", narragansett: "Namitch, commetesímmin", english: "Stay — you must eat first." },
        { id: "m4", speaker: "Host", narragansett: "Téaquacumméich", english: "What will you eat?" },
        { id: "m5", speaker: "Guest", narragansett: "Aupúminea-nawsaùmp", english: "Parched meal boiled (soft corn porridge)." },
        { id: "m6", speaker: "Host", narragansett: "Wunnégin", english: "Welcome." },
        { id: "m7", speaker: "Guest", narragansett: "Taubotneanawáyean", english: "I thank you." },
        { id: "m8", speaker: "Host", narragansett: "Cowaúnckamish", english: "My respects to you." },
      ],
      28,
    ),
  }),
  scene({
    id: "meal-kids",
    title: "Share the bowl (kids)",
    summary: "Cinematic food-sharing — same two friends, shot-per-line with speaking mouths.",
    chapter: "Eating and Entertainment",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 2,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/meal-kids.mp4",
    posterSrc: "/scenes/meal-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "food", "cinematic", "speak"],
    lines: timed(
      [
        { id: "mk1", speaker: "Friend", narragansett: "Niccàwkatone", english: "I am thirsty.", audioSrc: "/audio/kids/mk1.mp3" },
        { id: "mk2", speaker: "Friend", narragansett: "Nip, or nipéwese", english: "Some water, please.", audioSrc: "/audio/kids/mk2.mp3" },
        { id: "mk3", speaker: "Friend", narragansett: "Namitch, commetesímmin", english: "Stay — eat first.", audioSrc: "/audio/kids/mk3.mp3" },
        { id: "mk4", speaker: "Friend", narragansett: "Téaquacumméich", english: "What will you eat?", audioSrc: "/audio/kids/mk4.mp3" },
        { id: "mk5", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/kids/mk5.mp3" },
      ],
      30,
    ),
  }),

  // ——— Sleep & lodging ———
  scene({
    id: "sleep-lodge",
    title: "Rest for the night",
    summary: "Sleep and lodging — welcome rest, mats, wood on the fire.",
    chapter: "Sleep and Lodging",
    chapterNum: 3,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 25,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sleep-lodge.mp4",
    posterSrc: "/scenes/sleep-lodge.jpg",
    durationSec: 28,
    tags: ["sleep", "home", "lodge"],
    lines: timed(
      [
        { id: "sl1", speaker: "Guest", narragansett: "Yo nickowémen?", english: "Shall I sleep here?", wordId: "rw-03-yo-nickow-men" },
        { id: "sl2", speaker: "Host", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here.", wordId: "rw-03-wunn-gin-c-wish" },
        { id: "sl3", speaker: "Host", narragansett: "Wuddtúckqunash, ponamáuta", english: "Let us lay on wood.", wordId: "rw-03-wuddt-ckqunash-ponam-uta" },
        { id: "sl4", speaker: "Guest", narragansett: "Nkàtaquaum", english: "I am sleepy.", wordId: "rw-03-nk-taquaum" },
        { id: "sl5", speaker: "Host", narragansett: "Cowwêtuck", english: "Let us sleep.", wordId: "rw-03-coww-tuck" },
        { id: "sl6", speaker: "Host", narragansett: "Mattannauke", english: "Fine mats to sleep on.", wordId: "rw-03-mattannauke-or" },
        { id: "sl7", speaker: "Guest", narragansett: "Cowwêwi", english: "He is asleep.", wordId: "rw-03-coww-wi" },
        { id: "sl8", speaker: "Host", narragansett: "Tokêtuck", english: "Let us wake.", wordId: "rw-03-tok-tuck" },
      ],
      28,
    ),
  }),

  // ——— Numbers ———
  scene({
    id: "count-shells",
    title: "Counting shells",
    summary: "Numbers one through ten — hands and shells along the shore.",
    chapter: "Numbers",
    chapterNum: 4,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Skills",
    pathOrder: 30,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/count-shells.mp4",
    posterSrc: "/scenes/count-shells.jpg",
    durationSec: 30,
    tags: ["numbers", "count"],
    lines: timed(
      [
        { id: "n1", speaker: "Host", narragansett: "Nquít", english: "One." },
        { id: "n2", speaker: "Host", narragansett: "Neèse", english: "Two." },
        { id: "n3", speaker: "Host", narragansett: "Nìsh", english: "Three." },
        { id: "n4", speaker: "Host", narragansett: "Yòh", english: "Four." },
        { id: "n5", speaker: "Host", narragansett: "Napánna", english: "Five." },
        { id: "n6", speaker: "Host", narragansett: "Qútta", english: "Six." },
        { id: "n7", speaker: "Host", narragansett: "Énada", english: "Seven." },
        { id: "n8", speaker: "Host", narragansett: "Shwósuck", english: "Eight." },
        { id: "n9", speaker: "Host", narragansett: "Paskúgit", english: "Nine." },
        { id: "n10", speaker: "Host", narragansett: "Piùck", english: "Ten." },
      ],
      30,
    ),
  }),

  // ——— Kin ———
  scene({
    id: "family-kin",
    title: "Our family",
    summary: "Kinship words — father, mother, child, elders of the family.",
    chapter: "Relations of Consanguinity",
    chapterNum: 5,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 35,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/family-kin.mp4",
    posterSrc: "/scenes/family-kin.jpg",
    durationSec: 28,
    tags: ["family", "kin", "people"],
    lines: timed(
      [
        { id: "fk1", speaker: "Host", narragansett: "Nósh", english: "My father.", wordId: "rw-05-n-sh" },
        { id: "fk2", speaker: "Host", narragansett: "Cŏsh", english: "Your father.", wordId: "rw-05-c-sh" },
        { id: "fk3", speaker: "Host", narragansett: "Okásu", english: "A mother.", wordId: "rw-05-ok-su" },
        { id: "fk4", speaker: "Host", narragansett: "Nókace, níchwhaw", english: "My mother.", wordId: "rw-05-n-kace-n-chwhaw" },
        { id: "fk5", speaker: "Host", narragansett: "Nippápoos", english: "My child." },
        { id: "fk6", speaker: "Host", narragansett: "Hômes", english: "An old man (elder).", wordId: "rw-05-h-mes" },
        { id: "fk7", speaker: "Host", narragansett: "Wénise", english: "An old woman (elder).", wordId: "rw-05-w-nise" },
        { id: "fk8", speaker: "Host", narragansett: "Kichize", english: "An old man.", wordId: "rw-05-kichize" },
      ],
      28,
    ),
  }),

  // ——— House ———
  scene({
    id: "home-fire",
    title: "Home by the fire",
    summary: "House and rest — wetu, at home, sleep, welcome rest.",
    chapter: "House and Family",
    chapterNum: 6,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 40,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/home-fire.mp4",
    posterSrc: "/scenes/home-fire.jpg",
    durationSec: 28,
    tags: ["home", "family", "sleep"],
    lines: timed(
      [
        { id: "h1", speaker: "Host", narragansett: "Wetu", english: "A house / dwelling." },
        { id: "h2", speaker: "Host", narragansett: "Wetuômuck", english: "At home." },
        { id: "h3", speaker: "Host", narragansett: "Nkàtaquaum", english: "I am sleepy." },
        { id: "h4", speaker: "Host", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here." },
        { id: "h5", speaker: "Host", narragansett: "Nsowwushkâwmen", english: "I am weary." },
        { id: "h6", speaker: "Host", narragansett: "Cowwêtuck", english: "Let us sleep." },
        { id: "h7", speaker: "Host", narragansett: "Wuddtúckqunash, ponamáuta", english: "Let us lay on wood." },
        { id: "h8", speaker: "Host", narragansett: "Wunnégin", english: "Welcome." },
      ],
      28,
    ),
  }),

  // ——— Discourse ———
  scene({
    id: "news-marsh",
    title: "News by the marsh",
    summary: "Discourse and news — let us talk, tell me, I will tell you, I am finished.",
    chapter: "Discourse and News",
    chapterNum: 8,
    domain: "other",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 50,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/news-marsh.mp4",
    posterSrc: "/scenes/news-marsh.jpg",
    durationSec: 28,
    tags: ["news", "talk"],
    lines: timed(
      [
        { id: "d1", speaker: "Host", narragansett: "Aunchemokauhettíttea", english: "Let us talk / tell the news." },
        { id: "d2", speaker: "Host", narragansett: "Aaunchemókaw", english: "Tell me your news." },
        { id: "d3", speaker: "Guest", narragansett: "Cuttaunchemókous", english: "I will tell you the news." },
        { id: "d4", speaker: "Guest", narragansett: "Cummautaunchemókous", english: "I have finished my news." },
        { id: "d5", speaker: "Host", narragansett: "Taubút paump maúntaman", english: "I am glad (to hear it)." },
        { id: "d6", speaker: "Guest", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "d7", speaker: "Host", narragansett: "Taubotneanawáyean", english: "I thank you." },
        { id: "d8", speaker: "Guest", narragansett: "Wunnégin", english: "Welcome." },
      ],
      28,
    ),
  }),

  // ——— Time of day ———
  scene({
    id: "day-hours",
    title: "Hours of the day",
    summary: "From sunrise to dark night — telling time by the sun.",
    chapter: "Time of the Day",
    chapterNum: 9,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 55,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/day-hours.mp4",
    posterSrc: "/scenes/day-hours.jpg",
    durationSec: 28,
    tags: ["time", "sun", "day"],
    lines: timed(
      [
        { id: "dh1", speaker: "Host", narragansett: "Páshisha", english: "It is sunrise.", wordId: "rw-09-p-shisha" },
        { id: "dh2", speaker: "Host", narragansett: "Mautàbon, Chicháuquat wompan", english: "It is day.", wordId: "rw-09-maut-bon-chich-uquat-wompan" },
        { id: "dh3", speaker: "Host", narragansett: "Nummáttaqúaw", english: "Morning (before noon).", wordId: "rw-09-numm-ttaq-aw" },
        { id: "dh4", speaker: "Host", narragansett: "Páweshaquaw", english: "Noon.", wordId: "rw-09-p-weshaquaw" },
        { id: "dh5", speaker: "Host", narragansett: "Nawwâuwqaw", english: "Afternoon.", wordId: "rw-09-naww-uwqaw" },
        { id: "dh6", speaker: "Host", narragansett: "Yahen wàiyàuw", english: "Almost sunset.", wordId: "rw-09-yahen-w-iy-uw" },
        { id: "dh7", speaker: "Host", narragansett: "Wayaàwi", english: "The sun is set.", wordId: "rw-09-waya-wi" },
        { id: "dh8", speaker: "Host", narragansett: "Póppakunnetch, auchaugotch", english: "Dark night.", wordId: "rw-09-p-ppakunnetch-auchaugotch" },
      ],
      28,
    ),
  }),

  // ——— Seasons ———
  scene({
    id: "seasons-year",
    title: "Through the year",
    summary: "Spring, summer, harvest, winter — the year's turning.",
    chapter: "Seasons of the Year",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 60,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/seasons-year.mp4",
    posterSrc: "/scenes/seasons-year.jpg",
    durationSec: 28,
    tags: ["seasons", "year"],
    lines: timed(
      [
        { id: "sy1", speaker: "Host", narragansett: "Séquan", english: "Spring.", wordId: "rw-10-s-quan" },
        { id: "sy2", speaker: "Host", narragansett: "Aukeeteámitch", english: "Spring — seed-time.", wordId: "rw-10-aukeete-mitch" },
        { id: "sy3", speaker: "Host", narragansett: "Néepun", english: "Summer.", wordId: "rw-10-n-epun-quaq-squan" },
        { id: "sy4", speaker: "Host", narragansett: "Taquònck", english: "Fall / autumn.", wordId: "rw-10-taqu-nck" },
        { id: "sy5", speaker: "Host", narragansett: "Papóne", english: "Winter.", wordId: "rw-10-pap-ne" },
        { id: "sy6", speaker: "Host", narragansett: "Yo neepúnnacup", english: "This summer last.", wordId: "rw-10-yo-neep-nnacup" },
        { id: "sy7", speaker: "Host", narragansett: "Yò taquónticup", english: "This harvest last.", wordId: "rw-10-y-taqu-nticup" },
        { id: "sy8", speaker: "Host", narragansett: "Yaûnedg", english: "The last year.", wordId: "rw-10-ya-nedg" },
      ],
      28,
    ),
  }),
  scene({
    id: "seasons-kids",
    title: "Four seasons (kids)",
    summary: "Four seasons with the same two friends — cinematic storybook, shot-per-line.",
    chapter: "Seasons of the Year",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 7,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/seasons-kids.mp4",
    posterSrc: "/scenes/seasons-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "seasons", "cinematic", "speak"],
    lines: timed(
      [
        { id: "sk1", speaker: "Friend", narragansett: "Séquan", english: "Spring.", audioSrc: "/audio/kids/sk1.mp3" },
        { id: "sk2", speaker: "Friend", narragansett: "Néepun", english: "Summer.", audioSrc: "/audio/kids/sk2.mp3" },
        { id: "sk3", speaker: "Friend", narragansett: "Taquònck", english: "Fall.", audioSrc: "/audio/kids/sk3.mp3" },
        { id: "sk4", speaker: "Friend", narragansett: "Papóne", english: "Winter.", audioSrc: "/audio/kids/sk4.mp3" },
        { id: "sk5", speaker: "Friend", narragansett: "Aukeeteámitch", english: "Seed-time.", audioSrc: "/audio/kids/sk5.mp3" },
      ],
      30,
    ),
  }),

  // ——— Travel ———
  scene({
    id: "ask-path",
    title: "Show me the way",
    summary: "On the trail — asking directions with care.",
    chapter: "Travel",
    chapterNum: 11,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 70,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/ask-path.mp4",
    posterSrc: "/scenes/ask-path.jpg",
    durationSec: 28,
    tags: ["travel", "path"],
    lines: timed(
      [
        { id: "p1", speaker: "Host", narragansett: "Nnatotemúckaun", english: "I will ask the way." },
        { id: "p2", speaker: "Host", narragansett: "Kunnatótemous", english: "I will inquire of you." },
        { id: "p3", speaker: "Host", narragansett: "Kokotemíinnea méyi", english: "Show me the way." },
        { id: "p4", speaker: "Guest", narragansett: "Mishimmáyagat", english: "A great path." },
        { id: "p5", speaker: "Guest", narragansett: "Peemáyagât", english: "A short way." },
        { id: "p6", speaker: "Host", narragansett: "Taubotneanawáyean", english: "I thank you." },
        { id: "p7", speaker: "Guest", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "p8", speaker: "Host", narragansett: "Nickquénum", english: "I am going." },
      ],
      28,
    ),
  }),

  // ——— Heavenly lights ———
  scene({
    id: "sky-moon",
    title: "Moon and stars",
    summary: "Heavenly lights — sun, moon, stars over the coast.",
    chapter: "The Heavenly Lights",
    chapterNum: 12,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 75,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sky-moon.mp4",
    posterSrc: "/scenes/sky-moon.jpg",
    durationSec: 28,
    tags: ["moon", "stars", "sky"],
    lines: timed(
      [
        { id: "sm1", speaker: "Host", narragansett: "Kéesuck", english: "The heavens.", wordId: "rw-12-k-esuck" },
        { id: "sm2", speaker: "Host", narragansett: "Nippâwus", english: "The sun.", wordId: "rw-12-nipp-wus" },
        { id: "sm3", speaker: "Host", narragansett: "Nanepaùshat", english: "The moon.", wordId: "rw-12-nanepa-shat-and" },
        { id: "sm4", speaker: "Host", narragansett: "Yò Ockquitteunk", english: "A new moon.", wordId: "rw-12-y-ockquitteunk" },
        { id: "sm5", speaker: "Host", narragansett: "Yo wompanámmit", english: "Half moon.", wordId: "rw-12-yo-wompan-mmit" },
        { id: "sm6", speaker: "Host", narragansett: "Anóckqus, anócksuck", english: "A star, stars.", wordId: "rw-12-an-ckqus-an-cksuck" },
        { id: "sm7", speaker: "Host", narragansett: "Mishánnock", english: "The morning star.", wordId: "rw-12-mish-nnock" },
        { id: "sm8", speaker: "Host", narragansett: "Pashpíshea", english: "The moon is up.", wordId: "rw-12-pashp-shea" },
      ],
      28,
    ),
  }),

  // ——— Weather ———
  scene({
    id: "weather-sky",
    title: "Reading the weather",
    summary: "Looking up — fair, cold, hot, and the wind.",
    chapter: "The Weather",
    chapterNum: 13,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 80,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/weather-sky.mp4",
    posterSrc: "/scenes/weather-sky.jpg",
    durationSec: 28,
    tags: ["weather", "sky"],
    lines: timed(
      [
        { id: "w1", speaker: "Host", narragansett: "T Ocke tussinnámmin kéesuck", english: "What do you think of the weather?" },
        { id: "w2", speaker: "Host", narragansett: "Wekineaûquat", english: "Fair weather." },
        { id: "w3", speaker: "Host", narragansett: "Tahkì or tátakki", english: "Cold weather." },
        { id: "w4", speaker: "Host", narragansett: "Kussúttah", english: "It is hot." },
        { id: "w5", speaker: "Host", narragansett: "W Aûpi", english: "The wind." },
        { id: "w6", speaker: "Host", narragansett: "Wunnágehan", english: "Fair wind." },
        { id: "w7", speaker: "Host", narragansett: "Sáchimoachepewéssin", english: "A strong northeast wind." },
        { id: "w8", speaker: "Host", narragansett: "Nqénowhick wouttín", english: "I stay for a wind." },
      ],
      28,
    ),
  }),

  // ——— Winds ———
  scene({
    id: "wind-rise",
    title: "Reading the winds",
    summary: "Wind names and waiting for a fair breeze.",
    chapter: "The Winds",
    chapterNum: 14,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 85,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/wind-rise.mp4",
    posterSrc: "/scenes/wind-rise.jpg",
    durationSec: 28,
    tags: ["wind", "weather"],
    lines: timed(
      [
        { id: "wr1", speaker: "Host", narragansett: "W Aûpi", english: "The wind.", wordId: "rw-14-w-a-pi" },
        { id: "wr2", speaker: "Host", narragansett: "Tashínash waupanash", english: "How many winds are there?", wordId: "rw-14-tash-nash-waupanash" },
        { id: "wr3", speaker: "Host", narragansett: "Nanúmmatin", english: "The north wind.", wordId: "rw-14-nan-mmatin" },
        { id: "wr4", speaker: "Host", narragansett: "Nopâtin", english: "The east wind.", wordId: "rw-14-nop-tin" },
        { id: "wr5", speaker: "Host", narragansett: "Touwúttin", english: "South wind.", wordId: "rw-14-touw-ttin" },
        { id: "wr6", speaker: "Host", narragansett: "Papônetin", english: "West wind.", wordId: "rw-14-pap-netin" },
        { id: "wr7", speaker: "Host", narragansett: "Wunnágehan", english: "Fair wind.", wordId: "rw-14-wunn-gehan-or" },
        { id: "wr8", speaker: "Host", narragansett: "Nqénowhick wouttín", english: "I stay for a wind.", wordId: "rw-14-nq-nowhick-woutt-n" },
      ],
      28,
    ),
  }),

  // ——— Fowl ———
  scene({
    id: "birds-marsh",
    title: "Birds of the marsh",
    summary: "Fowl of the land and water — turkey, goose, blackbird, wing.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 90,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/birds-marsh.mp4",
    posterSrc: "/scenes/birds-marsh.jpg",
    durationSec: 28,
    tags: ["birds", "fowl", "marsh"],
    lines: timed(
      [
        { id: "bm1", speaker: "Host", narragansett: "Néyhom, mâuog", english: "Turkey, turkeys.", wordId: "rw-15-n-yhom-m-uog" },
        { id: "bm2", speaker: "Host", narragansett: "Hònck, hònckock", english: "Goose, geese.", wordId: "rw-15-h-nck-h-nckock" },
        { id: "bm3", speaker: "Host", narragansett: "Chógan èuck", english: "Blackbird, blackbirds.", wordId: "rw-15-ch-gan-uck" },
        { id: "bm4", speaker: "Host", narragansett: "Paupock, sûog", english: "Partridge, partridges.", wordId: "rw-15-paupock-s-og" },
        { id: "bm5", speaker: "Host", narragansett: "Wunnùp, pash", english: "Wing, wings.", wordId: "rw-15-wunn-p-pash" },
        { id: "bm6", speaker: "Host", narragansett: "Yo aquéchinock", english: "There they swim." },
        { id: "bm7", speaker: "Host", narragansett: "Aunckuck, quâuog", english: "Heath cocks." },
        { id: "bm8", speaker: "Host", narragansett: "Wunnúppaníckánawhone", english: "Wing-shot.", wordId: "rw-15-wunn-ppan-ck-nawhone" },
      ],
      28,
    ),
  }),
  scene({
    id: "birds-kids",
    title: "Bird friends (kids)",
    summary: "Bird friends with the same two friends — cinematic storybook, shot-per-line.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 8,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/birds-kids.mp4",
    posterSrc: "/scenes/birds-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "birds", "cinematic", "speak"],
    lines: timed(
      [
        { id: "bk1", speaker: "Friend", narragansett: "Hònck", english: "Goose.", audioSrc: "/audio/kids/bk1.mp3" },
        { id: "bk2", speaker: "Friend", narragansett: "Néyhom", english: "Turkey.", audioSrc: "/audio/kids/bk2.mp3" },
        { id: "bk3", speaker: "Friend", narragansett: "Chógan", english: "Blackbird.", audioSrc: "/audio/kids/bk3.mp3" },
        { id: "bk4", speaker: "Friend", narragansett: "Wunnùp", english: "Wing.", audioSrc: "/audio/kids/bk4.mp3" },
        { id: "bk5", speaker: "Friend", narragansett: "Paupock", english: "Partridge.", audioSrc: "/audio/kids/bk5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "count-kids",
    title: "Count with me (kids)",
    summary: "Count one to five with shells — same two friends, cinematic speak-first.",
    chapter: "Of their numbers",
    chapterNum: 4,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 3,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/count-kids.mp4",
    posterSrc: "/scenes/count-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "numbers", "cinematic", "speak"],
    lines: timed(
      [
        { id: "ck1", speaker: "Friend", narragansett: "Nquít", english: "One.", audioSrc: "/audio/kids/ck1.mp3" },
        { id: "ck2", speaker: "Friend", narragansett: "Neèse", english: "Two.", audioSrc: "/audio/kids/ck2.mp3" },
        { id: "ck3", speaker: "Friend", narragansett: "Nìsh", english: "Three.", audioSrc: "/audio/kids/ck3.mp3" },
        { id: "ck4", speaker: "Friend", narragansett: "Yòh", english: "Four.", audioSrc: "/audio/kids/ck4.mp3" },
        { id: "ck5", speaker: "Friend", narragansett: "Napánna", english: "Five.", audioSrc: "/audio/kids/ck5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "family-kids",
    title: "Family words (kids)",
    summary: "HQ family words — father, mother, child, elders shown with the two friends as leads.",
    chapter: "Of the family",
    chapterNum: 5,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 4,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/family-kids.mp4",
    posterSrc: "/scenes/family-kids.jpg",
    durationSec: 30,
    tags: ["kids", "hq", "family", "cinematic", "speak"],
    lines: timed(
      [
        { id: "fkids1", speaker: "Friend", narragansett: "Nósh", english: "My father.", audioSrc: "/audio/kids/fkids1.mp3" },
        { id: "fkids2", speaker: "Friend", narragansett: "Okásu", english: "A mother.", audioSrc: "/audio/kids/fkids2.mp3" },
        { id: "fkids3", speaker: "Friend", narragansett: "Nippápoos", english: "My child.", audioSrc: "/audio/kids/fkids3.mp3" },
        { id: "fkids4", speaker: "Friend", narragansett: "Hômes", english: "An old man (elder).", audioSrc: "/audio/kids/fkids4.mp3" },
        { id: "fkids5", speaker: "Friend", narragansett: "Wénise", english: "An old woman (elder).", audioSrc: "/audio/kids/fkids5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "home-kids",
    title: "Home wetu (kids)",
    summary: "HQ wetu home — accurate bark-mat dome, shot-per-line with the two friends.",
    chapter: "Of the family and house",
    chapterNum: 6,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 5,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/home-kids.mp4",
    posterSrc: "/scenes/home-kids.jpg",
    durationSec: 30,
    tags: ["kids", "hq", "home", "cinematic", "speak"],
    lines: timed(
      [
        { id: "hk1", speaker: "Friend", narragansett: "Wetu", english: "A house / dwelling.", audioSrc: "/audio/kids/hk1.mp3" },
        { id: "hk2", speaker: "Friend", narragansett: "Wetuômuck", english: "At home.", audioSrc: "/audio/kids/hk2.mp3" },
        { id: "hk3", speaker: "Friend", narragansett: "Wunnégin", english: "Welcome.", audioSrc: "/audio/kids/hk3.mp3" },
        { id: "hk4", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/kids/hk4.mp3" },
        { id: "hk5", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/kids/hk5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "day-kids",
    title: "Day light (kids)",
    summary: "Sunrise to night with the same two friends — cinematic speak-first.",
    chapter: "Of the time of the day",
    chapterNum: 9,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 6,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/day-kids.mp4",
    posterSrc: "/scenes/day-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "day", "cinematic", "speak"],
    lines: timed(
      [
        { id: "dk1", speaker: "Friend", narragansett: "Páshisha", english: "It is sunrise.", audioSrc: "/audio/kids/dk1.mp3" },
        { id: "dk2", speaker: "Friend", narragansett: "Mautàbon", english: "It is day.", audioSrc: "/audio/kids/dk2.mp3" },
        { id: "dk3", speaker: "Friend", narragansett: "Nummáttaqúaw", english: "Morning.", audioSrc: "/audio/kids/dk3.mp3" },
        { id: "dk4", speaker: "Friend", narragansett: "Wayaàwi", english: "The sun is set.", audioSrc: "/audio/kids/dk4.mp3" },
        { id: "dk5", speaker: "Friend", narragansett: "Póppakunnetch", english: "Dark night.", audioSrc: "/audio/kids/dk5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "water-kids",
    title: "By the water (kids)",
    summary: "Shore words with the same two friends — cinematic speak-first.",
    chapter: "Of the sea",
    chapterNum: 18,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 9,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/water-kids.mp4",
    posterSrc: "/scenes/water-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "water", "cinematic", "speak"],
    lines: timed(
      [
        { id: "wk1", speaker: "Friend", narragansett: "Nip", english: "Water.", audioSrc: "/audio/kids/wk1.mp3" },
        { id: "wk2", speaker: "Friend", narragansett: "Namaùus", english: "Fish.", audioSrc: "/audio/kids/wk2.mp3" },
        { id: "wk3", speaker: "Friend", narragansett: "Ntaûmen", english: "I am fishing.", audioSrc: "/audio/kids/wk3.mp3" },
        { id: "wk4", speaker: "Friend", narragansett: "Wunnágehan", english: "Fair wind.", audioSrc: "/audio/kids/wk4.mp3" },
        { id: "wk5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/kids/wk5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "sleep-kids",
    title: "Night rest (kids)",
    summary: "Night rest with the same two friends — cinematic speak-first.",
    chapter: "Of sleep and lodging",
    chapterNum: 3,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 10,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sleep-kids.mp4",
    posterSrc: "/scenes/sleep-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "sleep", "cinematic", "speak"],
    lines: timed(
      [
        { id: "skids1", speaker: "Friend", narragansett: "Yo nickowémen?", english: "Shall I sleep here?", audioSrc: "/audio/kids/skids1.mp3" },
        { id: "skids2", speaker: "Friend", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here.", audioSrc: "/audio/kids/skids2.mp3" },
        { id: "skids3", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/kids/skids3.mp3" },
        { id: "skids4", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/kids/skids4.mp3" },
        { id: "skids5", speaker: "Friend", narragansett: "Mattannauke", english: "Fine mats to sleep on.", audioSrc: "/audio/kids/skids5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "path-kids",
    title: "Little path (kids)",
    summary: "Path words with the same two friends — cinematic speak-first.",
    chapter: "Of travel",
    chapterNum: 11,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 11,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/path-kids.mp4",
    posterSrc: "/scenes/path-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "path", "cinematic", "speak"],
    lines: timed(
      [
        { id: "pk1", speaker: "Friend", narragansett: "Kokotemíinnea méyi", english: "Show me the way.", audioSrc: "/audio/kids/pk1.mp3" },
        { id: "pk2", speaker: "Friend", narragansett: "Peemáyagât", english: "A short way.", audioSrc: "/audio/kids/pk2.mp3" },
        { id: "pk3", speaker: "Friend", narragansett: "Mishimmáyagat", english: "A great path.", audioSrc: "/audio/kids/pk3.mp3" },
        { id: "pk4", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/kids/pk4.mp3" },
        { id: "pk5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/kids/pk5.mp3" },
      ],
      30,
    ),
  }),
  scene({
    id: "land-kids",
    title: "Corn and land (kids)",
    summary: "Earth and corn with the same two friends — cinematic speak-first.",
    chapter: "Of the earth and fruits",
    chapterNum: 16,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Little Ones",
    pathOrder: 12,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/land-kids.mp4",
    posterSrc: "/scenes/land-kids.jpg",
    durationSec: 30,
    tags: ["hq", "kids", "land", "cinematic", "speak"],
    lines: timed(
      [
        { id: "lk1", speaker: "Friend", narragansett: "Aûke", english: "Earth or land.", audioSrc: "/audio/kids/lk1.mp3" },
        { id: "lk2", speaker: "Friend", narragansett: "Ewáchim neash", english: "Corn.", audioSrc: "/audio/kids/lk2.mp3" },
        { id: "lk3", speaker: "Friend", narragansett: "Scannémeneash", english: "Seed corn.", audioSrc: "/audio/kids/lk3.mp3" },
        { id: "lk4", speaker: "Friend", narragansett: "Aukeeteaûmen", english: "To plant corn.", audioSrc: "/audio/kids/lk4.mp3" },
        { id: "lk5", speaker: "Friend", narragansett: "Sókenug", english: "A heap of corn.", audioSrc: "/audio/kids/lk5.mp3" },
      ],
      30,
    ),
  }),

// ——— Young Path (Student) ———
  scene({
    id: "greeting-student",
    title: "Hello, friend",
    summary: "Greetings with Friend Tan and Friend Teal as teens — Young Path, cinematic speak-first.",
    chapter: "Of salutation",
    chapterNum: 1,
    domain: "other",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 1,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/greeting-student.mp4",
    posterSrc: "/scenes/greeting-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "greeting", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "gs1", speaker: "Friend", narragansett: "Ascowequassunnúmmis", english: "Good morning.", audioSrc: "/audio/student/gs1.mp3" },
        { id: "gs2", speaker: "Friend", narragansett: "Askuttaaquompsín", english: "How are you?", audioSrc: "/audio/student/gs2.mp3" },
        { id: "gs3", speaker: "Friend", narragansett: "Asnpaumpmaúntam", english: "I am very well.", audioSrc: "/audio/student/gs3.mp3" },
        { id: "gs4", speaker: "Friend", narragansett: "Cowaúnckamish", english: "My respects to you.", audioSrc: "/audio/student/gs4.mp3" },
        { id: "gs5", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/student/gs5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "meal-student",
    title: "Share the bowl",
    summary: "Food and welcome words with the same two friends, now teens.",
    chapter: "Of their eating",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 2,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/meal-student.mp4",
    posterSrc: "/scenes/meal-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "food", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ms1", speaker: "Friend", narragansett: "Niccàwkatone", english: "I am thirsty.", audioSrc: "/audio/student/ms1.mp3" },
        { id: "ms2", speaker: "Friend", narragansett: "Nip, or nipéwese", english: "Some water, please.", audioSrc: "/audio/student/ms2.mp3" },
        { id: "ms3", speaker: "Friend", narragansett: "Namitch, commetesímmin", english: "Stay — you must eat first.", audioSrc: "/audio/student/ms3.mp3" },
        { id: "ms4", speaker: "Friend", narragansett: "Téaquacumméich", english: "What will you eat?", audioSrc: "/audio/student/ms4.mp3" },
        { id: "ms5", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/student/ms5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "count-student",
    title: "Count with me",
    summary: "Count one to five — Young Path cinematic speak-first.",
    chapter: "Of their numbers",
    chapterNum: 4,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 3,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/count-student.mp4",
    posterSrc: "/scenes/count-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "numbers", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "cs1", speaker: "Friend", narragansett: "Nquít", english: "One.", audioSrc: "/audio/student/cs1.mp3" },
        { id: "cs2", speaker: "Friend", narragansett: "Neèse", english: "Two.", audioSrc: "/audio/student/cs2.mp3" },
        { id: "cs3", speaker: "Friend", narragansett: "Nìsh", english: "Three.", audioSrc: "/audio/student/cs3.mp3" },
        { id: "cs4", speaker: "Friend", narragansett: "Yòh", english: "Four.", audioSrc: "/audio/student/cs4.mp3" },
        { id: "cs5", speaker: "Friend", narragansett: "Napánna", english: "Five.", audioSrc: "/audio/student/cs5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "family-student",
    title: "Family words",
    summary: "Father, mother, child, elders — leads are Friend Tan and Friend Teal as teens.",
    chapter: "Of the family",
    chapterNum: 5,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 4,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/family-student.mp4",
    posterSrc: "/scenes/family-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "family", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "fs1", speaker: "Friend", narragansett: "Nósh", english: "My father.", audioSrc: "/audio/student/fs1.mp3" },
        { id: "fs2", speaker: "Friend", narragansett: "Okásu", english: "A mother.", audioSrc: "/audio/student/fs2.mp3" },
        { id: "fs3", speaker: "Friend", narragansett: "Nippápoos", english: "My child.", audioSrc: "/audio/student/fs3.mp3" },
        { id: "fs4", speaker: "Friend", narragansett: "Hômes", english: "An old man — an elder.", audioSrc: "/audio/student/fs4.mp3" },
        { id: "fs5", speaker: "Friend", narragansett: "Wénise", english: "An old woman — an elder.", audioSrc: "/audio/student/fs5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "home-student",
    title: "Home wetu",
    summary: "Wetu home words with the teen cast — bark-mat dome locked.",
    chapter: "Of the family and house",
    chapterNum: 6,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 5,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/home-student.mp4",
    posterSrc: "/scenes/home-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "home", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "hs1", speaker: "Friend", narragansett: "Wetu", english: "A house, a dwelling.", audioSrc: "/audio/student/hs1.mp3" },
        { id: "hs2", speaker: "Friend", narragansett: "Wetuômuck", english: "At home.", audioSrc: "/audio/student/hs2.mp3" },
        { id: "hs3", speaker: "Friend", narragansett: "Wunnégin", english: "Welcome.", audioSrc: "/audio/student/hs3.mp3" },
        { id: "hs4", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/student/hs4.mp3" },
        { id: "hs5", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/student/hs5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "day-student",
    title: "Day light",
    summary: "Sunrise to night with Friend Tan and Friend Teal as teens.",
    chapter: "Of the time of the day",
    chapterNum: 9,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 6,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/day-student.mp4",
    posterSrc: "/scenes/day-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "day", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ds1", speaker: "Friend", narragansett: "Páshisha", english: "It is sunrise.", audioSrc: "/audio/student/ds1.mp3" },
        { id: "ds2", speaker: "Friend", narragansett: "Mautàbon", english: "It is day.", audioSrc: "/audio/student/ds2.mp3" },
        { id: "ds3", speaker: "Friend", narragansett: "Nummáttaqúaw", english: "Morning, before noon.", audioSrc: "/audio/student/ds3.mp3" },
        { id: "ds4", speaker: "Friend", narragansett: "Wayaàwi", english: "The sun is set.", audioSrc: "/audio/student/ds4.mp3" },
        { id: "ds5", speaker: "Friend", narragansett: "Póppakunnetch", english: "Dark night.", audioSrc: "/audio/student/ds5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "seasons-student",
    title: "Four seasons",
    summary: "Spring through seed-time — Young Path cinematic speak-first.",
    chapter: "Of the seasons",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 7,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/seasons-student.mp4",
    posterSrc: "/scenes/seasons-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "seasons", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ss1", speaker: "Friend", narragansett: "Séquan", english: "Spring.", audioSrc: "/audio/student/ss1.mp3" },
        { id: "ss2", speaker: "Friend", narragansett: "Néepun", english: "Summer.", audioSrc: "/audio/student/ss2.mp3" },
        { id: "ss3", speaker: "Friend", narragansett: "Taquònck", english: "Fall, autumn.", audioSrc: "/audio/student/ss3.mp3" },
        { id: "ss4", speaker: "Friend", narragansett: "Papóne", english: "Winter.", audioSrc: "/audio/student/ss4.mp3" },
        { id: "ss5", speaker: "Friend", narragansett: "Aukeeteámitch", english: "Seed-time.", audioSrc: "/audio/student/ss5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "birds-student",
    title: "Bird friends",
    summary: "Bird words with the same two friends as teens.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 8,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/birds-student.mp4",
    posterSrc: "/scenes/birds-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "birds", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "bs1", speaker: "Friend", narragansett: "Hònck", english: "Goose.", audioSrc: "/audio/student/bs1.mp3" },
        { id: "bs2", speaker: "Friend", narragansett: "Néyhom", english: "Turkey.", audioSrc: "/audio/student/bs2.mp3" },
        { id: "bs3", speaker: "Friend", narragansett: "Chógan", english: "Blackbird.", audioSrc: "/audio/student/bs3.mp3" },
        { id: "bs4", speaker: "Friend", narragansett: "Wunnùp", english: "Wing.", audioSrc: "/audio/student/bs4.mp3" },
        { id: "bs5", speaker: "Friend", narragansett: "Paupock", english: "Partridge.", audioSrc: "/audio/student/bs5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "water-student",
    title: "By the water",
    summary: "Shore and water words — Young Path cinematic speak-first.",
    chapter: "Of the sea",
    chapterNum: 18,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 9,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/water-student.mp4",
    posterSrc: "/scenes/water-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "water", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ws1", speaker: "Friend", narragansett: "Nip", english: "Water.", audioSrc: "/audio/student/ws1.mp3" },
        { id: "ws2", speaker: "Friend", narragansett: "Namaùus", english: "Fish.", audioSrc: "/audio/student/ws2.mp3" },
        { id: "ws3", speaker: "Friend", narragansett: "Ntaûmen", english: "I am fishing.", audioSrc: "/audio/student/ws3.mp3" },
        { id: "ws4", speaker: "Friend", narragansett: "Wunnágehan", english: "Fair wind.", audioSrc: "/audio/student/ws4.mp3" },
        { id: "ws5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/student/ws5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "sleep-student",
    title: "Night rest",
    summary: "Sleep and lodging words with the teen cast.",
    chapter: "Of sleep and lodging",
    chapterNum: 3,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 10,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sleep-student.mp4",
    posterSrc: "/scenes/sleep-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "sleep", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "sls1", speaker: "Friend", narragansett: "Yo nickowémen?", english: "Shall I sleep here?", audioSrc: "/audio/student/sls1.mp3" },
        { id: "sls2", speaker: "Friend", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here.", audioSrc: "/audio/student/sls2.mp3" },
        { id: "sls3", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/student/sls3.mp3" },
        { id: "sls4", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/student/sls4.mp3" },
        { id: "sls5", speaker: "Friend", narragansett: "Mattannauke", english: "Fine mats to sleep on.", audioSrc: "/audio/student/sls5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "path-student",
    title: "On the path",
    summary: "Travel and path words with Friend Tan and Friend Teal as teens.",
    chapter: "Of travel",
    chapterNum: 11,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 11,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/path-student.mp4",
    posterSrc: "/scenes/path-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "path", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ps1", speaker: "Friend", narragansett: "Kokotemíinnea méyi", english: "Show me the way.", audioSrc: "/audio/student/ps1.mp3" },
        { id: "ps2", speaker: "Friend", narragansett: "Peemáyagât", english: "A short way.", audioSrc: "/audio/student/ps2.mp3" },
        { id: "ps3", speaker: "Friend", narragansett: "Mishimmáyagat", english: "A great path.", audioSrc: "/audio/student/ps3.mp3" },
        { id: "ps4", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/student/ps4.mp3" },
        { id: "ps5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/student/ps5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "land-student",
    title: "Corn and land",
    summary: "Earth and corn with the teen cast — Young Path cinematic speak-first.",
    chapter: "Of the earth and fruits",
    chapterNum: 16,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Young Path",
    pathOrder: 12,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/land-student.mp4",
    posterSrc: "/scenes/land-student.jpg",
    durationSec: 30,
    tags: ["hq", "student", "land", "cinematic", "speak", "young-path"],
    lines: timed(
      [
        { id: "ls1", speaker: "Friend", narragansett: "Aûke", english: "Earth or land.", audioSrc: "/audio/student/ls1.mp3" },
        { id: "ls2", speaker: "Friend", narragansett: "Ewáchim neash", english: "Corn.", audioSrc: "/audio/student/ls2.mp3" },
        { id: "ls3", speaker: "Friend", narragansett: "Scannémeneash", english: "Seed corn.", audioSrc: "/audio/student/ls3.mp3" },
        { id: "ls4", speaker: "Friend", narragansett: "Aukeeteaûmen", english: "To plant corn.", audioSrc: "/audio/student/ls4.mp3" },
        { id: "ls5", speaker: "Friend", narragansett: "Sókenug", english: "A heap of corn.", audioSrc: "/audio/student/ls5.mp3" },
      ],
      30,
    ),
  }),


// ——— Adult Path ———

  scene({
    id: "greeting-adult",
    title: "Hello, friend",
    summary: "Greetings with Friend Tan and Friend Teal as adults — Adult Path, cinematic speak-first.",
    chapter: "Of salutation",
    chapterNum: 1,
    domain: "other",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 1,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/greeting-adult.mp4",
    posterSrc: "/scenes/greeting-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "greeting", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "ga1", speaker: "Friend", narragansett: "Ascowequassunnúmmis", english: "Good morning.", audioSrc: "/audio/adult/ga1.mp3" },
        { id: "ga2", speaker: "Friend", narragansett: "Askuttaaquompsín", english: "How are you?", audioSrc: "/audio/adult/ga2.mp3" },
        { id: "ga3", speaker: "Friend", narragansett: "Asnpaumpmaúntam", english: "I am very well.", audioSrc: "/audio/adult/ga3.mp3" },
        { id: "ga4", speaker: "Friend", narragansett: "Cowaúnckamish", english: "My respects to you.", audioSrc: "/audio/adult/ga4.mp3" },
        { id: "ga5", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/adult/ga5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "meal-adult",
    title: "Share the bowl",
    summary: "Food and welcome words with the same two friends as adults.",
    chapter: "Of their eating",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 2,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/meal-adult.mp4",
    posterSrc: "/scenes/meal-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "food", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "ma1", speaker: "Friend", narragansett: "Niccàwkatone", english: "I am thirsty.", audioSrc: "/audio/adult/ma1.mp3" },
        { id: "ma2", speaker: "Friend", narragansett: "Nip, or nipéwese", english: "Some water, please.", audioSrc: "/audio/adult/ma2.mp3" },
        { id: "ma3", speaker: "Friend", narragansett: "Namitch, commetesímmin", english: "Stay — you must eat first.", audioSrc: "/audio/adult/ma3.mp3" },
        { id: "ma4", speaker: "Friend", narragansett: "Téaquacumméich", english: "What will you eat?", audioSrc: "/audio/adult/ma4.mp3" },
        { id: "ma5", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/adult/ma5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "count-adult",
    title: "Count with me",
    summary: "Count one to five — Adult Path cinematic speak-first.",
    chapter: "Of their numbers",
    chapterNum: 4,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 3,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/count-adult.mp4",
    posterSrc: "/scenes/count-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "numbers", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "ca1", speaker: "Friend", narragansett: "Nquít", english: "One.", audioSrc: "/audio/adult/ca1.mp3" },
        { id: "ca2", speaker: "Friend", narragansett: "Neèse", english: "Two.", audioSrc: "/audio/adult/ca2.mp3" },
        { id: "ca3", speaker: "Friend", narragansett: "Nìsh", english: "Three.", audioSrc: "/audio/adult/ca3.mp3" },
        { id: "ca4", speaker: "Friend", narragansett: "Yòh", english: "Four.", audioSrc: "/audio/adult/ca4.mp3" },
        { id: "ca5", speaker: "Friend", narragansett: "Napánna", english: "Five.", audioSrc: "/audio/adult/ca5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "family-adult",
    title: "Family words",
    summary: "Father, mother, child, elders — leads are Friend Tan and Friend Teal as adults.",
    chapter: "Of the family",
    chapterNum: 5,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 4,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/family-adult.mp4",
    posterSrc: "/scenes/family-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "family", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "fa1", speaker: "Friend", narragansett: "Nósh", english: "My father.", audioSrc: "/audio/adult/fa1.mp3" },
        { id: "fa2", speaker: "Friend", narragansett: "Okásu", english: "A mother.", audioSrc: "/audio/adult/fa2.mp3" },
        { id: "fa3", speaker: "Friend", narragansett: "Nippápoos", english: "My child.", audioSrc: "/audio/adult/fa3.mp3" },
        { id: "fa4", speaker: "Friend", narragansett: "Hômes", english: "An old man — an elder.", audioSrc: "/audio/adult/fa4.mp3" },
        { id: "fa5", speaker: "Friend", narragansett: "Wénise", english: "An old woman — an elder.", audioSrc: "/audio/adult/fa5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "home-adult",
    title: "Home wetu",
    summary: "Wetu home words with the adult cast — bark-mat dome locked.",
    chapter: "Of the family and house",
    chapterNum: 6,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 5,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/home-adult.mp4",
    posterSrc: "/scenes/home-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "home", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "ha1", speaker: "Friend", narragansett: "Wetu", english: "A house, a dwelling.", audioSrc: "/audio/adult/ha1.mp3" },
        { id: "ha2", speaker: "Friend", narragansett: "Wetuômuck", english: "At home.", audioSrc: "/audio/adult/ha2.mp3" },
        { id: "ha3", speaker: "Friend", narragansett: "Wunnégin", english: "Welcome.", audioSrc: "/audio/adult/ha3.mp3" },
        { id: "ha4", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/adult/ha4.mp3" },
        { id: "ha5", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/adult/ha5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "day-adult",
    title: "Day light",
    summary: "Sunrise to night with Friend Tan and Friend Teal as adults.",
    chapter: "Of the time of the day",
    chapterNum: 9,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 6,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/day-adult.mp4",
    posterSrc: "/scenes/day-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "day", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "da1", speaker: "Friend", narragansett: "Páshisha", english: "It is sunrise.", audioSrc: "/audio/adult/da1.mp3" },
        { id: "da2", speaker: "Friend", narragansett: "Mautàbon", english: "It is day.", audioSrc: "/audio/adult/da2.mp3" },
        { id: "da3", speaker: "Friend", narragansett: "Nummáttaqúaw", english: "Morning, before noon.", audioSrc: "/audio/adult/da3.mp3" },
        { id: "da4", speaker: "Friend", narragansett: "Wayaàwi", english: "The sun is set.", audioSrc: "/audio/adult/da4.mp3" },
        { id: "da5", speaker: "Friend", narragansett: "Póppakunnetch", english: "Dark night.", audioSrc: "/audio/adult/da5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "seasons-adult",
    title: "Four seasons",
    summary: "Spring through seed-time — Adult Path cinematic speak-first.",
    chapter: "Of the seasons",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 7,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/seasons-adult.mp4",
    posterSrc: "/scenes/seasons-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "seasons", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "sa1", speaker: "Friend", narragansett: "Séquan", english: "Spring.", audioSrc: "/audio/adult/sa1.mp3" },
        { id: "sa2", speaker: "Friend", narragansett: "Néepun", english: "Summer.", audioSrc: "/audio/adult/sa2.mp3" },
        { id: "sa3", speaker: "Friend", narragansett: "Taquònck", english: "Fall, autumn.", audioSrc: "/audio/adult/sa3.mp3" },
        { id: "sa4", speaker: "Friend", narragansett: "Papóne", english: "Winter.", audioSrc: "/audio/adult/sa4.mp3" },
        { id: "sa5", speaker: "Friend", narragansett: "Aukeeteámitch", english: "Seed-time.", audioSrc: "/audio/adult/sa5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "birds-adult",
    title: "Bird friends",
    summary: "Bird words with the same two friends as adults.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 8,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/birds-adult.mp4",
    posterSrc: "/scenes/birds-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "birds", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "ba1", speaker: "Friend", narragansett: "Hònck", english: "Goose.", audioSrc: "/audio/adult/ba1.mp3" },
        { id: "ba2", speaker: "Friend", narragansett: "Néyhom", english: "Turkey.", audioSrc: "/audio/adult/ba2.mp3" },
        { id: "ba3", speaker: "Friend", narragansett: "Chógan", english: "Blackbird.", audioSrc: "/audio/adult/ba3.mp3" },
        { id: "ba4", speaker: "Friend", narragansett: "Wunnùp", english: "Wing.", audioSrc: "/audio/adult/ba4.mp3" },
        { id: "ba5", speaker: "Friend", narragansett: "Paupock", english: "Partridge.", audioSrc: "/audio/adult/ba5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "water-adult",
    title: "By the water",
    summary: "Shore and water words — Adult Path cinematic speak-first.",
    chapter: "Of the sea",
    chapterNum: 18,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 9,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/water-adult.mp4",
    posterSrc: "/scenes/water-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "water", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "wa1", speaker: "Friend", narragansett: "Nip", english: "Water.", audioSrc: "/audio/adult/wa1.mp3" },
        { id: "wa2", speaker: "Friend", narragansett: "Namaùus", english: "Fish.", audioSrc: "/audio/adult/wa2.mp3" },
        { id: "wa3", speaker: "Friend", narragansett: "Ntaûmen", english: "I am fishing.", audioSrc: "/audio/adult/wa3.mp3" },
        { id: "wa4", speaker: "Friend", narragansett: "Wunnágehan", english: "Fair wind.", audioSrc: "/audio/adult/wa4.mp3" },
        { id: "wa5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/adult/wa5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "sleep-adult",
    title: "Night rest",
    summary: "Sleep and lodging words with the adult cast.",
    chapter: "Of sleep and lodging",
    chapterNum: 3,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 10,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/sleep-adult.mp4",
    posterSrc: "/scenes/sleep-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "sleep", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "sla1", speaker: "Friend", narragansett: "Yo nickowémen?", english: "Shall I sleep here?", audioSrc: "/audio/adult/sla1.mp3" },
        { id: "sla2", speaker: "Friend", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here.", audioSrc: "/audio/adult/sla2.mp3" },
        { id: "sla3", speaker: "Friend", narragansett: "Nkàtaquaum", english: "I am sleepy.", audioSrc: "/audio/adult/sla3.mp3" },
        { id: "sla4", speaker: "Friend", narragansett: "Cowwêtuck", english: "Let us sleep.", audioSrc: "/audio/adult/sla4.mp3" },
        { id: "sla5", speaker: "Friend", narragansett: "Mattannauke", english: "Fine mats to sleep on.", audioSrc: "/audio/adult/sla5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "path-adult",
    title: "On the path",
    summary: "Travel and path words with Friend Tan and Friend Teal as adults.",
    chapter: "Of travel",
    chapterNum: 11,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 11,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/path-adult.mp4",
    posterSrc: "/scenes/path-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "path", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "pa1", speaker: "Friend", narragansett: "Kokotemíinnea méyi", english: "Show me the way.", audioSrc: "/audio/adult/pa1.mp3" },
        { id: "pa2", speaker: "Friend", narragansett: "Peemáyagât", english: "A short way.", audioSrc: "/audio/adult/pa2.mp3" },
        { id: "pa3", speaker: "Friend", narragansett: "Mishimmáyagat", english: "A great path.", audioSrc: "/audio/adult/pa3.mp3" },
        { id: "pa4", speaker: "Friend", narragansett: "Taubotneanawáyean", english: "I thank you.", audioSrc: "/audio/adult/pa4.mp3" },
        { id: "pa5", speaker: "Friend", narragansett: "Nickquénum", english: "I am going.", audioSrc: "/audio/adult/pa5.mp3" },
      ],
      30,
    ),
  }),


  scene({
    id: "land-adult",
    title: "Corn and land",
    summary: "Earth and corn with the adult cast — Adult Path cinematic speak-first.",
    chapter: "Of the earth and fruits",
    chapterNum: 16,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Adult Path",
    pathOrder: 12,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/land-adult.mp4",
    posterSrc: "/scenes/land-adult.jpg",
    durationSec: 30,
    tags: ["hq", "adult", "land", "cinematic", "speak", "adult-path"],
    lines: timed(
      [
        { id: "la1", speaker: "Friend", narragansett: "Aûke", english: "Earth or land.", audioSrc: "/audio/adult/la1.mp3" },
        { id: "la2", speaker: "Friend", narragansett: "Ewáchim neash", english: "Corn.", audioSrc: "/audio/adult/la2.mp3" },
        { id: "la3", speaker: "Friend", narragansett: "Scannémeneash", english: "Seed corn.", audioSrc: "/audio/adult/la3.mp3" },
        { id: "la4", speaker: "Friend", narragansett: "Aukeeteaûmen", english: "To plant corn.", audioSrc: "/audio/adult/la4.mp3" },
        { id: "la5", speaker: "Friend", narragansett: "Sókenug", english: "A heap of corn.", audioSrc: "/audio/adult/la5.mp3" },
      ],
      30,
    ),
  }),

  
// ——— Elder Path (solemn public discourse — not living ceremony) ———

  scene({
    id: "council-elder",
    title: 'Council fire',
    summary: 'Meeting and counsel words with Friend Tan and Friend Teal as elders — Elder Path, solemn public discourse.',
    chapter: 'Of government and justice',
    chapterNum: 22,
    domain: 'governance',
    sensitivity: "careful",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 1,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/council-elder.mp4",
    posterSrc: "/scenes/council-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "council", "cinematic", "speak", "elder-path", "discourse"],
    lines: timed(
      [
        { id: "ec1", speaker: "Friend", narragansett: 'Miâwene', english: 'A court or meeting.', audioSrc: "/audio/elder/ec1.mp3" },
        { id: "ec2", speaker: "Friend", narragansett: 'Wépe cummiâwene', english: 'Come to the meeting.', audioSrc: "/audio/elder/ec2.mp3" },
        { id: "ec3", speaker: "Friend", narragansett: 'Miawêtuck', english: 'Let us meet.', audioSrc: "/audio/elder/ec3.mp3" },
        { id: "ec4", speaker: "Friend", narragansett: 'Wauóntam', english: 'A wise man or counsellor.', audioSrc: "/audio/elder/ec4.mp3" },
        { id: "ec5", speaker: "Friend", narragansett: 'Mishaúntowash', english: 'Speak out.', audioSrc: "/audio/elder/ec5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "word-elder",
    title: 'Let the word stand',
    summary: 'Plain speech, inquiry, mercy — Elder Path justice language (Williams public record).',
    chapter: 'Of government and justice',
    chapterNum: 22,
    domain: 'governance',
    sensitivity: "careful",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 2,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/word-elder.mp4",
    posterSrc: "/scenes/word-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "justice", "cinematic", "speak", "elder-path", "discourse"],
    lines: timed(
      [
        { id: "ew1", speaker: "Friend", narragansett: 'Nanántowash', english: 'Speak plain.', audioSrc: "/audio/elder/ew1.mp3" },
        { id: "ew2", speaker: "Friend", narragansett: 'Enatch neèn ánowa', english: 'Let my word stand.', audioSrc: "/audio/elder/ew2.mp3" },
        { id: "ew3", speaker: "Friend", narragansett: 'Wunnadsittamútta', english: 'Let us search into it.', audioSrc: "/audio/elder/ew3.mp3" },
        { id: "ew4", speaker: "Friend", narragansett: 'Nnowaúntum', english: 'I am sorry.', audioSrc: "/audio/elder/ew4.mp3" },
        { id: "ew5", speaker: "Friend", narragansett: 'Konkeeteatch Ewo', english: 'Let him live.', audioSrc: "/audio/elder/ew5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "discourse-elder",
    title: 'Evening words',
    summary: 'Discourse and news by the fire — deeper conversation than the daily packs.',
    chapter: 'Of discourse and news',
    chapterNum: 8,
    domain: 'other',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 3,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/discourse-elder.mp4",
    posterSrc: "/scenes/discourse-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "discourse", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "ed1", speaker: "Friend", narragansett: 'Aunchemokauhettíttea', english: 'Let us discourse, or tell news.', audioSrc: "/audio/elder/ed1.mp3" },
        { id: "ed2", speaker: "Friend", narragansett: 'Tocketeáunchim?', english: 'What news?', audioSrc: "/audio/elder/ed2.mp3" },
        { id: "ed3", speaker: "Friend", narragansett: 'Wetapwâuwwas', english: 'Sit and talk with us.', audioSrc: "/audio/elder/ed3.mp3" },
        { id: "ed4", speaker: "Friend", narragansett: 'Wunnáumwash', english: 'Speak the truth.', audioSrc: "/audio/elder/ed4.mp3" },
        { id: "ed5", speaker: "Friend", narragansett: 'Taúpowaw', english: 'A wise speaker.', audioSrc: "/audio/elder/ed5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "sky-elder",
    title: 'Sky and moon',
    summary: 'Heavens, sun, moon, and morning star — sky-reading language for elders.',
    chapter: 'Of the heavenly lights',
    chapterNum: 12,
    domain: 'weather',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 4,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/sky-elder.mp4",
    posterSrc: "/scenes/sky-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "sky", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "es1", speaker: "Friend", narragansett: 'Kéesuck', english: 'The heavens.', audioSrc: "/audio/elder/es1.mp3" },
        { id: "es2", speaker: "Friend", narragansett: 'Nippâwus', english: 'The sun.', audioSrc: "/audio/elder/es2.mp3" },
        { id: "es3", speaker: "Friend", narragansett: 'Pashpíshea', english: 'The moon is up.', audioSrc: "/audio/elder/es3.mp3" },
        { id: "es4", speaker: "Friend", narragansett: 'Yò Ockquitteunk', english: 'A new moon.', audioSrc: "/audio/elder/es4.mp3" },
        { id: "es5", speaker: "Friend", narragansett: 'Mishánnock', english: 'The morning star.', audioSrc: "/audio/elder/es5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "wampum-elder",
    title: 'Shell and strand',
    summary: 'Wampum shells, stringing, and wearing — formal public exchange language.',
    chapter: 'Of their coin',
    chapterNum: 24,
    domain: 'tools',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 5,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/wampum-elder.mp4",
    posterSrc: "/scenes/wampum-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "wampum", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "emp1", speaker: "Friend", narragansett: 'Anâwsuck', english: 'Shells.', audioSrc: "/audio/elder/emp1.mp3" },
        { id: "emp2", speaker: "Friend", narragansett: 'Enomphómmin', english: 'To thread or string.', audioSrc: "/audio/elder/emp2.mp3" },
        { id: "emp3", speaker: "Friend", narragansett: 'Aconaqúnnaûog', english: 'Thread the beads.', audioSrc: "/audio/elder/emp3.mp3" },
        { id: "emp4", speaker: "Friend", narragansett: 'Enomphósachick', english: 'Strung ones.', audioSrc: "/audio/elder/emp4.mp3" },
        { id: "emp5", speaker: "Friend", narragansett: 'Naumpacoûin', english: 'To hang about the neck.', audioSrc: "/audio/elder/emp5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "trade-elder",
    title: 'Fair trade',
    summary: 'Trade talk — like, price, and fair dealing with the elder cast.',
    chapter: 'Of buying and selling',
    chapterNum: 25,
    domain: 'tools',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 6,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/trade-elder.mp4",
    posterSrc: "/scenes/trade-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "trade", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "et1", speaker: "Friend", narragansett: 'Anaqushénto', english: 'Let us trade.', audioSrc: "/audio/elder/et1.mp3" },
        { id: "et2", speaker: "Friend", narragansett: 'Nowèkineam', english: 'I like this.', audioSrc: "/audio/elder/et2.mp3" },
        { id: "et3", speaker: "Friend", narragansett: 'Tahenautu?', english: 'What price?', audioSrc: "/audio/elder/et3.mp3" },
        { id: "et4", speaker: "Friend", narragansett: 'Wauwunnegachick', english: 'Very good.', audioSrc: "/audio/elder/et4.mp3" },
        { id: "et5", speaker: "Friend", narragansett: 'Aquie Wussaúmowash', english: 'Do not ask much.', audioSrc: "/audio/elder/et5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "match-elder",
    title: 'Making a match',
    summary: 'Marriage-custom language from Williams (public social record — not living sacred rite).',
    chapter: 'Of marriage',
    chapterNum: 23,
    domain: 'kinship',
    sensitivity: "careful",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 7,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/match-elder.mp4",
    posterSrc: "/scenes/match-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "marriage", "cinematic", "speak", "elder-path", "careful"],
    lines: timed(
      [
        { id: "em1", speaker: "Friend", narragansett: 'Wusséntam', english: 'He goes a-wooing.', audioSrc: "/audio/elder/em1.mp3" },
        { id: "em2", speaker: "Friend", narragansett: 'Wussenetûock', english: 'They make a match.', audioSrc: "/audio/elder/em2.mp3" },
        { id: "em3", speaker: "Friend", narragansett: 'Awetawátuonck', english: 'Of marriage.', audioSrc: "/audio/elder/em3.mp3" },
        { id: "em4", speaker: "Friend", narragansett: 'Waumaûsu', english: 'Loving.', audioSrc: "/audio/elder/em4.mp3" },
        { id: "em5", speaker: "Friend", narragansett: 'Aquèipokesháttous', english: 'Do not break the knot.', audioSrc: "/audio/elder/em5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "care-elder",
    title: 'Visit the sick',
    summary: 'Care and recovery words — visiting, sickness, covering, healing.',
    chapter: 'Of their sickness',
    chapterNum: 31,
    domain: 'medicine',
    sensitivity: "careful",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 8,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/care-elder.mp4",
    posterSrc: "/scenes/care-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "care", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "eka1", speaker: "Friend", narragansett: 'Nnanowweteem', english: 'I am going to visit.', audioSrc: "/audio/elder/eka1.mp3" },
        { id: "eka2", speaker: "Friend", narragansett: 'Achie nummaùchnem', english: 'I am very sick.', audioSrc: "/audio/elder/eka2.mp3" },
        { id: "eka3", speaker: "Friend", narragansett: 'Pitch nkéeteem?', english: 'Shall I recover?', audioSrc: "/audio/elder/eka3.mp3" },
        { id: "eka4", speaker: "Friend", narragansett: 'Kitummâyi nickêekon', english: 'I am just now recovered.', audioSrc: "/audio/elder/eka4.mp3" },
        { id: "eka5", speaker: "Friend", narragansett: 'Puttuckhúmma', english: 'Cover me.', audioSrc: "/audio/elder/eka5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "hunt-elder",
    title: 'The hunt',
    summary: 'Hunting words — go out, find deer, divide the gift.',
    chapter: 'Of hunting',
    chapterNum: 27,
    domain: 'fauna',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 9,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/hunt-elder.mp4",
    posterSrc: "/scenes/hunt-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "hunt", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "eh1", speaker: "Friend", narragansett: 'Auchaûtuck', english: 'Let us hunt.', audioSrc: "/audio/elder/eh1.mp3" },
        { id: "eh2", speaker: "Friend", narragansett: 'Ntauchaûmen', english: 'I go to hunt.', audioSrc: "/audio/elder/eh2.mp3" },
        { id: "eh3", speaker: "Friend", narragansett: 'Nummíshkommin', english: 'I have found a deer.', audioSrc: "/audio/elder/eh3.mp3" },
        { id: "eh4", speaker: "Friend", narragansett: 'Poskáttuck', english: 'A whole deer.', audioSrc: "/audio/elder/eh4.mp3" },
        { id: "eh5", speaker: "Friend", narragansett: 'Paushinummauatíttea', english: 'Let us divide.', audioSrc: "/audio/elder/eh5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "games-elder",
    title: 'Dance and play',
    summary: 'Public games and merry dance words from Williams sports chapter.',
    chapter: 'Of their sports',
    chapterNum: 28,
    domain: 'other',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 10,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/games-elder.mp4",
    posterSrc: "/scenes/games-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "games", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "eg1", speaker: "Friend", narragansett: 'Nippauochâumen', english: 'We are dancing.', audioSrc: "/audio/elder/eg1.mp3" },
        { id: "eg2", speaker: "Friend", narragansett: 'Pauochaúog', english: 'They are playing or dancing.', audioSrc: "/audio/elder/eg2.mp3" },
        { id: "eg3", speaker: "Friend", narragansett: 'Ahânuock', english: 'They are merry.', audioSrc: "/audio/elder/eg3.mp3" },
        { id: "eg4", speaker: "Friend", narragansett: 'Pasuckquakohowaûog', english: 'They meet to play.', audioSrc: "/audio/elder/eg4.mp3" },
        { id: "eg5", speaker: "Friend", narragansett: 'Tawhitchahânean', english: 'Why do you laugh?', audioSrc: "/audio/elder/eg5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "peace-elder",
    title: 'Make peace',
    summary: 'Peace-making language — cease anger, parley, agree, make friends (Wars chapter, public forms only).',
    chapter: 'Of their wars',
    chapterNum: 29,
    domain: 'governance',
    sensitivity: "sensitive",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 11,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/peace-elder.mp4",
    posterSrc: "/scenes/peace-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "peace", "cinematic", "speak", "elder-path", "sensitive"],
    lines: timed(
      [
        { id: "ep1", speaker: "Friend", narragansett: 'Aquène', english: 'Peace.', audioSrc: "/audio/elder/ep1.mp3" },
        { id: "ep2", speaker: "Friend", narragansett: 'Aquie musquàntash', english: 'Cease from anger.', audioSrc: "/audio/elder/ep2.mp3" },
        { id: "ep3", speaker: "Friend", narragansett: 'Kekuttokaúnta', english: 'Let us parley.', audioSrc: "/audio/elder/ep3.mp3" },
        { id: "ep4", speaker: "Friend", narragansett: 'Wunnishaûnta', english: 'Let us agree.', audioSrc: "/audio/elder/ep4.mp3" },
        { id: "ep5", speaker: "Friend", narragansett: 'Wetompátitea', english: 'Let us make friends.', audioSrc: "/audio/elder/ep5.mp3" },
      ],
      30,
    ),
  }),

  scene({
    id: "weather-elder",
    title: 'Read the sky',
    summary: 'Fair weather, rain, thunder, wind, and storm — seasonal reading for elders.',
    chapter: 'Of the weather',
    chapterNum: 13,
    domain: 'weather',
    sensitivity: "everyday",
    style: "cinematic",
    series: "Elder Path",
    pathOrder: 12,
    modesAllowed: ["elder"],
    videoSrc: "/scenes/weather-elder.mp4",
    posterSrc: "/scenes/weather-elder.jpg",
    durationSec: 30,
    tags: ["hq", "elder", "weather", "cinematic", "speak", "elder-path"],
    lines: timed(
      [
        { id: "evt1", speaker: "Friend", narragansett: 'Wekineaûquat', english: 'Fair weather.', audioSrc: "/audio/elder/evt1.mp3" },
        { id: "evt2", speaker: "Friend", narragansett: 'Sókenun', english: 'Rain.', audioSrc: "/audio/elder/evt2.mp3" },
        { id: "evt3", speaker: "Friend", narragansett: 'Neimpâuog', english: 'Thunder.', audioSrc: "/audio/elder/evt3.mp3" },
        { id: "evt4", speaker: "Friend", narragansett: 'Wunnágehan', english: 'Fair wind.', audioSrc: "/audio/elder/evt4.mp3" },
        { id: "evt5", speaker: "Friend", narragansett: 'Mishitáshin', english: 'A storm.', audioSrc: "/audio/elder/evt5.mp3" },
      ],
      30,
    ),
  }),

// ——— Earth & fruits ———
  scene({
    id: "earth-fruits",
    title: "Gifts of the earth",
    summary: "Land and corn — planting, seed-time, the living earth.",
    chapter: "Earth and Fruits",
    chapterNum: 16,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 95,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/earth-fruits.mp4",
    posterSrc: "/scenes/earth-fruits.jpg",
    durationSec: 28,
    tags: ["land", "plants", "corn"],
    lines: timed(
      [
        { id: "e1", speaker: "Host", narragansett: "Aûke", english: "Earth or land.", wordId: "rw-16-a-ke-and" },
        { id: "e2", speaker: "Host", narragansett: "Ewáchim neash", english: "Corn.", wordId: "rw-16-ew-chim-neash" },
        { id: "e3", speaker: "Host", narragansett: "Scannémeneash", english: "Seed corn.", wordId: "rw-16-scann-meneash" },
        { id: "e4", speaker: "Host", narragansett: "Aukeeteaûmen", english: "To plant corn.", wordId: "rw-16-aukeetea-men" },
        { id: "e5", speaker: "Host", narragansett: "Aukeeteámitch", english: "Spring — seed-time.", wordId: "rw-10-aukeete-mitch" },
        { id: "e6", speaker: "Host", narragansett: "Petascúnnemun", english: "To hill the corn.", wordId: "rw-16-petasc-nnemun" },
        { id: "e7", speaker: "Host", narragansett: "Kepenúmmin", english: "To gather corn.", wordId: "rw-16-kepen-mmin" },
        { id: "e8", speaker: "Host", narragansett: "Sókenug", english: "A heap of corn.", wordId: "rw-16-s-kenug" },
      ],
      28,
    ),
  }),

  // ——— Beasts ———
  scene({
    id: "forest-deer",
    title: "Deer in the forest",
    summary: "Beasts of the land — deer and otter of the woods and water.",
    chapter: "Beasts",
    chapterNum: 17,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 100,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/forest-deer.mp4",
    posterSrc: "/scenes/forest-deer.jpg",
    durationSec: 24,
    tags: ["deer", "animals", "forest"],
    lines: timed(
      [
        { id: "fd1", speaker: "Host", narragansett: "Attuck, quock", english: "Deer.", wordId: "rw-17-attuck-quock" },
        { id: "fd2", speaker: "Host", narragansett: "Wawwúnnes", english: "A young buck.", wordId: "rw-17-waww-nnes" },
        { id: "fd3", speaker: "Host", narragansett: "Kuttíomp", english: "A great buck.", wordId: "rw-17-kutt-omp-paucott-uwaw" },
        { id: "fd4", speaker: "Host", narragansett: "Nkéke, nkéquock", english: "Otter, otters.", wordId: "rw-17-nk-ke-nk-quock" },
        { id: "fd5", speaker: "Host", narragansett: "Moattôqus", english: "A black wolf.", wordId: "rw-17-moatt-qus" },
        { id: "fd6", speaker: "Host", narragansett: "Natuphéttitch yo sanaukamick", english: "Let them feed on this ground." },
      ],
      24,
    ),
  }),

  // ——— Sea ———
  scene({
    id: "canoe-shore",
    title: "At the shore",
    summary: "Canoe and water — the sea road in motion.",
    chapter: "The Sea",
    chapterNum: 18,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 105,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/canoe-shore.mp4",
    posterSrc: "/scenes/canoe-shore.jpg",
    durationSec: 28,
    tags: ["water", "canoe", "sea"],
    lines: timed(
      [
        { id: "c1", speaker: "Host", narragansett: "Nickquénum", english: "I am going." },
        { id: "c2", speaker: "Host", narragansett: "Acâwmuck nóteshem", english: "I came over the water." },
        { id: "c3", speaker: "Host", narragansett: "Nippâwus", english: "The sun." },
        { id: "c4", speaker: "Host", narragansett: "W Aûpi", english: "The wind." },
        { id: "c5", speaker: "Host", narragansett: "Wunnágehan", english: "Fair wind." },
        { id: "c6", speaker: "Host", narragansett: "Nqénowhick wouttín", english: "I stay for a wind." },
        { id: "c7", speaker: "Host", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "c8", speaker: "Host", narragansett: "Taubotneanawáyean", english: "I thank you." },
      ],
      28,
    ),
  }),

  // ——— Fish ———
  scene({
    id: "fish-water",
    title: "Fish and fishing",
    summary: "Fishing vocabulary — fish, bass, going out to fish.",
    chapter: "Fish and Fishing",
    chapterNum: 19,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 110,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/fish-water.mp4",
    posterSrc: "/scenes/fish-water.jpg",
    durationSec: 28,
    tags: ["fish", "water", "shore"],
    lines: timed(
      [
        { id: "f1", speaker: "Host", narragansett: "Namaùus,-suck", english: "Fish, fishes.", wordId: "rw-19-nama-us-suck" },
        { id: "f2", speaker: "Host", narragansett: "Ntaûmen", english: "I am fishing.", wordId: "rw-19-nta-men" },
        { id: "f3", speaker: "Host", narragansett: "Nnattuckqunnûwem", english: "I go a fishing.", wordId: "rw-19-nnattuckqunn-wem" },
        { id: "f4", speaker: "Host", narragansett: "Missúckeke-kéquock", english: "Bass.", wordId: "rw-19-miss-ckeke-k-quock" },
        { id: "f5", speaker: "Host", narragansett: "Mishquammaùquock", english: "Red fish, salmon.", wordId: "rw-19-mishquamma-quock" },
        { id: "f6", speaker: "Host", narragansett: "Aúmanep", english: "A fishing line.", wordId: "rw-19-a-manep" },
        { id: "f7", speaker: "Host", narragansett: "Aumaûog", english: "They are fishing.", wordId: "rw-19-auma-og" },
        { id: "f8", speaker: "Host", narragansett: "Kuttaûmen?", english: "Do you fish?", wordId: "rw-19-kutta-men" },
      ],
      28,
    ),
  }),

  // ——— Trade ———
  scene({
    id: "trade-shore",
    title: "Trade at the shore",
    summary: "Exchange and trust — market language with care.",
    chapter: "Buying and Selling",
    chapterNum: 25,
    domain: "tools",
    sensitivity: "careful",
    style: "cinematic",
    series: "Trade",
    pathOrder: 120,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/trade-shore.mp4",
    posterSrc: "/scenes/trade-shore.jpg",
    durationSec: 28,
    tags: ["trade", "wampum", "market"],
    lines: timed(
      [
        { id: "t1", speaker: "Host", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "t2", speaker: "Host", narragansett: "Téaquacumméich", english: "What will you have?" },
        { id: "t3", speaker: "Guest", narragansett: "Taubút paump maúntaman", english: "I am glad (of this)." },
        { id: "t4", speaker: "Host", narragansett: "Cummautaunchemókous", english: "I have finished my news." },
        { id: "t5", speaker: "Guest", narragansett: "Taubotneanawáyean", english: "I thank you." },
        { id: "t6", speaker: "Host", narragansett: "Wunnégin", english: "Welcome." },
        { id: "t7", speaker: "Both", narragansett: "Cowaúnckamish", english: "My respects to you." },
        { id: "t8", speaker: "Guest", narragansett: "Nickquénum", english: "I am going." },
      ],
      28,
    ),
  }),

  // ——— Hunting ———
  scene({
    id: "hunt-trail",
    title: "On the hunt trail",
    summary:
      "Hunting language of going out and returning — respectful trail words (no violence shown).",
    chapter: "Hunting",
    chapterNum: 27,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 115,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/hunt-trail.mp4",
    posterSrc: "/scenes/hunt-trail.jpg",
    durationSec: 28,
    tags: ["hunt", "trail", "forest"],
    lines: timed(
      [
        { id: "ht1", speaker: "Host", narragansett: "Ntauchaûmen", english: "I go to hunt.", wordId: "rw-27-ntaucha-men" },
        { id: "ht2", speaker: "Host", narragansett: "Auchaûtuck", english: "Let us hunt.", wordId: "rw-27-aucha-tuck" },
        { id: "ht3", speaker: "Host", narragansett: "Nowetauchaûmen", english: "I will hunt with you.", wordId: "rw-27-nowetaucha-men" },
        { id: "ht4", speaker: "Host", narragansett: "Npunnowwâumen", english: "I must go to my traps.", wordId: "rw-27-npunnoww-umen" },
        { id: "ht5", speaker: "Host", narragansett: "Apè hana", english: "Trap, traps.", wordId: "rw-27-ap-hana" },
        { id: "ht6", speaker: "Host", narragansett: "Ntaumpauchaúmen", english: "I come from hunting.", wordId: "rw-27-ntaumpaucha-men" },
        { id: "ht7", speaker: "Host", narragansett: "Ncáttiteam weeyoùs", english: "I long for venison.", wordId: "rw-27-nc-ttiteam-weeyo-s" },
        { id: "ht8", speaker: "Host", narragansett: "Nummouashàwmen", english: "I go to set traps.", wordId: "rw-27-nummouash-wmen" },
      ],
      28,
    ),
  }),

  // ——— Upload-ready scaffolds ———
  scene({
    id: "wampum-count",
    title: "Shell money words",
    summary: "Shell money and fathom counts — dedicated reconstruction for wampum vocabulary practice.",
    chapter: "Coin and Wampum",
    chapterNum: 24,
    domain: "tools",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Trade",
    pathOrder: 125,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/wampum-count.mp4",
    posterSrc: "/scenes/wampum-count.jpg",
    durationSec: 24,
    mediaStatus: "ready",
    tags: ["wampum", "trade"],
    reconstructionNote:
      "Dedicated shell-money reconstruction (object still + motion). Not living speaker footage. Prefer community media at public/scenes/uploads/wampum-count.mp4.",
    lines: timed(
      [
        { id: "wc1", speaker: "Host", narragansett: "Neesaúmscat", english: "Two pence (shell money unit).", wordId: "rw-24-neesa-mscat" },
        { id: "wc2", speaker: "Host", narragansett: "Quttatashaúmscat, or quttauatu", english: "Six pence.", wordId: "rw-24-quttatasha-mscat-or-quttauatu" },
        { id: "wc3", speaker: "Guest", narragansett: "Piuckquaúmscat", english: "Ten pence.", wordId: "rw-24-piuckqua-mscat" },
        { id: "wc4", speaker: "Host", narragansett: "Neesaumpaúgatuck", english: "Two fathom (ten shillings).", wordId: "rw-24-neesaumpa-gatuck" },
        { id: "wc5", speaker: "Guest", narragansett: "Shwaumpáugatuck", english: "Three fathom (fifteen shillings).", wordId: "rw-24-shwaump-ugatuck" },
        { id: "wc6", speaker: "Both", narragansett: "Cowaúnckamish", english: "My respects to you." },
      ],
      24,
    ),
  }),
  scene({
    id: "clothing-words",
    title: "Clothing words",
    summary: "Mantles and moccasins — careful clothing vocabulary with a dedicated reconstruction (Adult/Elder).",
    chapter: "Clothing",
    chapterNum: 20,
    domain: "tools",
    sensitivity: "careful",
    style: "cinematic",
    series: "Trade",
    pathOrder: 130,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/clothing-words.mp4",
    posterSrc: "/scenes/clothing-words.jpg",
    durationSec: 24,
    mediaStatus: "ready",
    tags: ["clothing", "careful"],
    reconstructionNote:
      "Careful chapter — dedicated object still reconstruction (mantle, moccasins). Not living speaker footage and not a fashion film. Prefer community media at public/scenes/uploads/clothing-words.mp4.",
    lines: timed(
      [
        { id: "cl1", speaker: "Host", narragansett: "Mocússinass", english: "Moccasins / shoes.", wordId: "rw-20-moc-ssinass-mockussinchass" },
        { id: "cl2", speaker: "Guest", narragansett: "Saunketíppo, or, Ashónaquo", english: "A hat or cap.", wordId: "rw-20-saunket-ppo-or-ash-naquo" },
        { id: "cl3", speaker: "Host", narragansett: "Maúnek: nquittiashíagat", english: "An English coat or mantle.", wordId: "rw-20-ma-nek-nquittiash-agat" },
        { id: "cl4", speaker: "Guest", narragansett: "Squáus aúhaqut", english: "A woman's mantle.", wordId: "rw-20-squ-us-a-haqut" },
        { id: "cl5", speaker: "Host", narragansett: "Muckíis auhaqut", english: "A child's mantle.", wordId: "rw-20-muck-is-auhaqut" },
      ],
      24,
    ),
  }),
];

export function getAllScenes(): LearningScene[] {
  return SCENES;
}
