import type { LearningModeId } from "./types";

export type SubtitleTrack = "off" | "narragansett" | "english" | "both";
export type VideoStyle = "cinematic" | "cartoon";
export type SceneSensitivity = "everyday" | "careful" | "sensitive";
export type MediaStatus = "ready" | "awaiting_upload";

export type SceneLine = {
  id: string;
  speaker: string;
  narragansett: string;
  english: string;
  startSec: number;
  endSec: number;
  /** Optional link into demo Williams lexicon word id */
  wordId?: string;
};

export type LearningScene = {
  id: string;
  title: string;
  summary: string;
  chapter: string;
  chapterNum: number;
  domain: string;
  sensitivity: SceneSensitivity;
  style: VideoStyle;
  modesAllowed: LearningModeId[];
  /** Default packaged reconstruction */
  videoSrc: string;
  posterSrc: string;
  /** Optional community/custom file: /scenes/uploads/{id}.mp4 */
  uploadSrc: string;
  durationSec: number;
  lines: SceneLine[];
  reconstructionNote: string;
  tags: string[];
  series?: string;
  mediaStatus?: MediaStatus;
  /** Suggested learning order within a mode (lower first) */
  pathOrder?: number;
};

const note =
  "AI visual reconstruction for language learning. Dialogue forms from Williams 1643 (modern English). Not a living speaker recording. Replace video files anytime via public/scenes/uploads — see docs/SCENES_UPLOAD.md.";

function scene(
  partial: Omit<LearningScene, "uploadSrc" | "reconstructionNote"> & {
    reconstructionNote?: string;
  },
): LearningScene {
  return {
    reconstructionNote: partial.reconstructionNote ?? note,
    uploadSrc: `/scenes/uploads/${partial.id}.mp4`,
    mediaStatus: partial.mediaStatus ?? "ready",
    ...partial,
  };
}

/**
 * Historical demo scenes — expand anytime; drop matching uploads/{id}.mp4 to override video.
 * Forms stay Williams 1643 with modern English glosses; living Keepers replace later.
 */
export const SCENES: LearningScene[] = [
  // ——— Salutation ———
  scene({
    id: "greeting-dawn",
    title: "Greeting at dawn",
    summary:
      "A respectful welcome outside the dwelling — how are you, I am well, my service to you.",
    chapter: "Salutation",
    chapterNum: 1,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 10,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/greeting-dawn.mp4",
    posterSrc: "/scenes/greeting-dawn.jpg",
    durationSec: 8,
    tags: ["greeting", "welcome", "hospitality"],
    lines: [
      { id: "g1", speaker: "Host", narragansett: "Ascowequassunnúmmis", english: "Good morning.", startSec: 0, endSec: 1.8 },
      { id: "g2", speaker: "Guest", narragansett: "Askuttaaquompsín", english: "How are you?", startSec: 1.8, endSec: 3.4 },
      { id: "g3", speaker: "Host", narragansett: "Asnpaumpmaúntam", english: "I am very well.", startSec: 3.4, endSec: 5.2 },
      { id: "g4", speaker: "Guest", narragansett: "Taubút paump maúntaman", english: "I am glad you are well.", startSec: 5.2, endSec: 6.8 },
      { id: "g5", speaker: "Host", narragansett: "Cowaúnckamish", english: "My respects to you.", startSec: 6.8, endSec: 8 },
    ],
  }),
  scene({
    id: "greeting-kids",
    title: "Hello, friend (kids)",
    summary: "A gentle cartoon hello for Little Ones — short greetings only.",
    chapter: "Salutation",
    chapterNum: 1,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cartoon",
    series: "Little Ones",
    pathOrder: 1,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/greeting-kids.mp4",
    posterSrc: "/scenes/greeting-kids.jpg",
    durationSec: 6,
    tags: ["kids", "greeting", "cartoon"],
    lines: [
      { id: "k1", speaker: "Friend", narragansett: "Ascowequassunnúmmis", english: "Good morning.", startSec: 0, endSec: 2 },
      { id: "k2", speaker: "Friend", narragansett: "Askuttaaquompsín", english: "How are you?", startSec: 2, endSec: 4 },
      { id: "k3", speaker: "Friend", narragansett: "Asnpaumpmaúntam", english: "I am very well.", startSec: 4, endSec: 6 },
    ],
  }),

  // ——— Eating ———
  scene({
    id: "meal-share",
    title: "Stay and eat",
    summary: "Hospitality at the fire — thirst, water, and sharing food.",
    chapter: "Eating and Entertainment",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 20,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/meal-share.mp4",
    posterSrc: "/scenes/meal-share.jpg",
    durationSec: 8,
    tags: ["food", "hospitality"],
    lines: [
      { id: "m1", speaker: "Guest", narragansett: "Niccàwkatone", english: "I am thirsty.", startSec: 0, endSec: 1.6 },
      { id: "m2", speaker: "Host", narragansett: "Nip, or nipéwese", english: "Give me some water.", startSec: 1.6, endSec: 3.2 },
      { id: "m3", speaker: "Host", narragansett: "Namitch, commetesímmin", english: "Stay — you must eat first.", startSec: 3.2, endSec: 5.2 },
      { id: "m4", speaker: "Host", narragansett: "Téaquacumméich", english: "What will you eat?", startSec: 5.2, endSec: 6.6 },
      { id: "m5", speaker: "Guest", narragansett: "Aupúminea-nawsaùmp", english: "Parched meal boiled (soft corn porridge).", startSec: 6.6, endSec: 8 },
    ],
  }),
  scene({
    id: "meal-kids",
    title: "Share the bowl (kids)",
    summary: "Cartoon food-sharing for the youngest — short, warm lines.",
    chapter: "Eating and Entertainment",
    chapterNum: 2,
    domain: "food",
    sensitivity: "everyday",
    style: "cartoon",
    series: "Little Ones",
    pathOrder: 2,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/meal-kids.mp4",
    posterSrc: "/scenes/meal-kids.jpg",
    durationSec: 6,
    tags: ["kids", "food", "cartoon"],
    lines: [
      { id: "mk1", speaker: "Friend", narragansett: "Niccàwkatone", english: "I am thirsty.", startSec: 0, endSec: 2 },
      { id: "mk2", speaker: "Friend", narragansett: "Nip, or nipéwese", english: "Some water, please.", startSec: 2, endSec: 4 },
      { id: "mk3", speaker: "Friend", narragansett: "Namitch, commetesímmin", english: "Stay — eat first.", startSec: 4, endSec: 6 },
    ],
  }),

  // ——— Sleep & lodging ———
  scene({
    id: "sleep-lodge",
    title: "Rest for the night",
    summary: "Sleep and lodging — welcome rest, mats, wood on the fire.",
    chapter: "Sleep and Lodging",
    chapterNum: 3,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 25,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sleep-lodge.mp4",
    posterSrc: "/scenes/sleep-lodge.jpg",
    durationSec: 6,
    tags: ["sleep", "home", "lodge"],
    lines: [
      {
        id: "sl1",
        speaker: "Guest",
        narragansett: "Yo nickowémen?",
        english: "Shall I sleep here?",
        startSec: 0,
        endSec: 1.4,
        wordId: "rw-03-yo-nickow-men",
      },
      {
        id: "sl2",
        speaker: "Host",
        narragansett: "Wunnégin, cówish",
        english: "Welcome — sleep here.",
        startSec: 1.4,
        endSec: 2.8,
        wordId: "rw-03-wunn-gin-c-wish",
      },
      {
        id: "sl3",
        speaker: "Host",
        narragansett: "Wuddtúckqunash, ponamáuta",
        english: "Let us lay on wood.",
        startSec: 2.8,
        endSec: 4.2,
        wordId: "rw-03-wuddt-ckqunash-ponam-uta",
      },
      {
        id: "sl4",
        speaker: "Guest",
        narragansett: "Nkàtaquaum",
        english: "I am sleepy.",
        startSec: 4.2,
        endSec: 5.2,
        wordId: "rw-03-nk-taquaum",
      },
      {
        id: "sl5",
        speaker: "Host",
        narragansett: "Cowwêtuck",
        english: "Let us sleep.",
        startSec: 5.2,
        endSec: 6,
        wordId: "rw-03-coww-tuck",
      },
    ],
  }),

  // ——— Numbers ———
  scene({
    id: "count-shells",
    title: "Counting shells",
    summary: "Numbers one through ten — hands and shells.",
    chapter: "Numbers",
    chapterNum: 4,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Skills",
    pathOrder: 30,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/count-shells.mp4",
    posterSrc: "/scenes/count-shells.jpg",
    durationSec: 6,
    tags: ["numbers", "count"],
    lines: [
      { id: "n1", speaker: "Speaker", narragansett: "Nquít", english: "One.", startSec: 0, endSec: 1.2 },
      { id: "n2", speaker: "Speaker", narragansett: "Neèse", english: "Two.", startSec: 1.2, endSec: 2.2 },
      { id: "n3", speaker: "Speaker", narragansett: "Nìsh", english: "Three.", startSec: 2.2, endSec: 3.2 },
      { id: "n4", speaker: "Speaker", narragansett: "Yòh", english: "Four.", startSec: 3.2, endSec: 4.2 },
      { id: "n5", speaker: "Speaker", narragansett: "Napánna", english: "Five.", startSec: 4.2, endSec: 5.1 },
      { id: "n6", speaker: "Speaker", narragansett: "Piùck", english: "Ten.", startSec: 5.1, endSec: 6 },
    ],
  }),

  // ——— Kin ———
  scene({
    id: "family-kin",
    title: "Our family",
    summary: "Kinship words — father, mother, child, elders of the family.",
    chapter: "Relations of Consanguinity",
    chapterNum: 5,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 35,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/family-kin.mp4",
    posterSrc: "/scenes/family-kin.jpg",
    durationSec: 6,
    tags: ["family", "kin", "people"],
    lines: [
      {
        id: "fk1",
        speaker: "Speaker",
        narragansett: "Nósh",
        english: "My father.",
        startSec: 0,
        endSec: 1.2,
        wordId: "rw-05-n-sh",
      },
      {
        id: "fk2",
        speaker: "Speaker",
        narragansett: "Okásu",
        english: "A mother.",
        startSec: 1.2,
        endSec: 2.4,
        wordId: "rw-05-ok-su",
      },
      {
        id: "fk3",
        speaker: "Speaker",
        narragansett: "Nippápoos",
        english: "My child.",
        startSec: 2.4,
        endSec: 3.6,
      },
      {
        id: "fk4",
        speaker: "Speaker",
        narragansett: "Hômes",
        english: "An old man (elder).",
        startSec: 3.6,
        endSec: 4.8,
        wordId: "rw-05-h-mes",
      },
      {
        id: "fk5",
        speaker: "Speaker",
        narragansett: "Wénise",
        english: "An old woman (elder).",
        startSec: 4.8,
        endSec: 6,
        wordId: "rw-05-w-nise",
      },
    ],
  }),

  // ——— House ———
  scene({
    id: "home-fire",
    title: "Home by the fire",
    summary: "House and rest — wetu, sleep, welcome rest.",
    chapter: "House and Family",
    chapterNum: 6,
    domain: "kinship",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 40,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/home-fire.mp4",
    posterSrc: "/scenes/home-fire.jpg",
    durationSec: 8,
    tags: ["home", "family", "sleep"],
    lines: [
      { id: "h1", speaker: "Speaker", narragansett: "Wetu", english: "A house / dwelling.", startSec: 0, endSec: 1.8 },
      { id: "h2", speaker: "Speaker", narragansett: "Wetuômuck", english: "At home.", startSec: 1.8, endSec: 3.4 },
      { id: "h3", speaker: "Speaker", narragansett: "Nkàtaquaum", english: "I am sleepy.", startSec: 3.4, endSec: 5.2 },
      { id: "h4", speaker: "Speaker", narragansett: "Wunnégin, cówish", english: "Welcome — sleep here.", startSec: 5.2, endSec: 6.8 },
      { id: "h5", speaker: "Speaker", narragansett: "Nsowwushkâwmen", english: "I am weary.", startSec: 6.8, endSec: 8 },
    ],
  }),

  // ——— Discourse ———
  scene({
    id: "news-marsh",
    title: "News by the marsh",
    summary: "Discourse and news — tell me, I will tell you, I am finished.",
    chapter: "Discourse and News",
    chapterNum: 8,
    domain: "other",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 50,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/news-marsh.mp4",
    posterSrc: "/scenes/news-marsh.jpg",
    durationSec: 8,
    tags: ["news", "talk"],
    lines: [
      { id: "d1", speaker: "A", narragansett: "Aunchemokauhettíttea", english: "Let us talk / tell the news.", startSec: 0, endSec: 2 },
      { id: "d2", speaker: "A", narragansett: "Aaunchemókaw", english: "Tell me your news.", startSec: 2, endSec: 3.6 },
      { id: "d3", speaker: "B", narragansett: "Cuttaunchemókous", english: "I will tell you the news.", startSec: 3.6, endSec: 5.4 },
      { id: "d4", speaker: "B", narragansett: "Cummautaunchemókous", english: "I have finished my news.", startSec: 5.4, endSec: 7 },
      { id: "d5", speaker: "A", narragansett: "Taubút paump maúntaman", english: "I am glad (to hear it).", startSec: 7, endSec: 8 },
    ],
  }),

  // ——— Time of day ———
  scene({
    id: "day-hours",
    title: "Hours of the day",
    summary: "From sunrise to dark night — telling time by the sun.",
    chapter: "Time of the Day",
    chapterNum: 9,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 55,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/day-hours.mp4",
    posterSrc: "/scenes/day-hours.jpg",
    durationSec: 6,
    tags: ["time", "sun", "day"],
    lines: [
      {
        id: "dh1",
        speaker: "Speaker",
        narragansett: "Páshisha",
        english: "It is sunrise.",
        startSec: 0,
        endSec: 1.2,
        wordId: "rw-09-p-shisha",
      },
      {
        id: "dh2",
        speaker: "Speaker",
        narragansett: "Mautàbon, Chicháuquat wompan",
        english: "It is day.",
        startSec: 1.2,
        endSec: 2.4,
        wordId: "rw-09-maut-bon-chich-uquat-wompan",
      },
      {
        id: "dh3",
        speaker: "Speaker",
        narragansett: "Páweshaquaw",
        english: "Noon.",
        startSec: 2.4,
        endSec: 3.5,
        wordId: "rw-09-p-weshaquaw",
      },
      {
        id: "dh4",
        speaker: "Speaker",
        narragansett: "Yahen wàiyàuw",
        english: "Almost sunset.",
        startSec: 3.5,
        endSec: 4.7,
        wordId: "rw-09-yahen-w-iy-uw",
      },
      {
        id: "dh5",
        speaker: "Speaker",
        narragansett: "Póppakunnetch, auchaugotch",
        english: "Dark night.",
        startSec: 4.7,
        endSec: 6,
        wordId: "rw-09-p-ppakunnetch-auchaugotch",
      },
    ],
  }),

  // ——— Seasons ———
  scene({
    id: "seasons-year",
    title: "Through the year",
    summary: "Spring, summer, harvest, winter — the year's turning.",
    chapter: "Seasons of the Year",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 60,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/seasons-year.mp4",
    posterSrc: "/scenes/seasons-year.jpg",
    durationSec: 6,
    tags: ["seasons", "year"],
    lines: [
      {
        id: "sy1",
        speaker: "Speaker",
        narragansett: "Séquan",
        english: "Spring.",
        startSec: 0,
        endSec: 1.3,
        wordId: "rw-10-s-quan",
      },
      {
        id: "sy2",
        speaker: "Speaker",
        narragansett: "Néepun",
        english: "Summer.",
        startSec: 1.3,
        endSec: 2.6,
        wordId: "rw-10-n-epun-quaq-squan",
      },
      {
        id: "sy3",
        speaker: "Speaker",
        narragansett: "Taquònck",
        english: "Fall / autumn.",
        startSec: 2.6,
        endSec: 4,
        wordId: "rw-10-taqu-nck",
      },
      {
        id: "sy4",
        speaker: "Speaker",
        narragansett: "Papóne",
        english: "Winter.",
        startSec: 4,
        endSec: 5.2,
        wordId: "rw-10-pap-ne",
      },
      {
        id: "sy5",
        speaker: "Speaker",
        narragansett: "Aukeeteámitch",
        english: "Spring — seed-time.",
        startSec: 5.2,
        endSec: 6,
        wordId: "rw-10-aukeete-mitch",
      },
    ],
  }),
  scene({
    id: "seasons-kids",
    title: "Four seasons (kids)",
    summary: "A soft cartoon walk through spring, summer, fall, and winter.",
    chapter: "Seasons of the Year",
    chapterNum: 10,
    domain: "time",
    sensitivity: "everyday",
    style: "cartoon",
    series: "Little Ones",
    pathOrder: 3,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/seasons-kids.mp4",
    posterSrc: "/scenes/seasons-kids.jpg",
    durationSec: 6,
    tags: ["kids", "seasons", "cartoon"],
    lines: [
      { id: "sk1", speaker: "Friend", narragansett: "Séquan", english: "Spring.", startSec: 0, endSec: 1.5 },
      { id: "sk2", speaker: "Friend", narragansett: "Néepun", english: "Summer.", startSec: 1.5, endSec: 3 },
      { id: "sk3", speaker: "Friend", narragansett: "Taquònck", english: "Fall.", startSec: 3, endSec: 4.5 },
      { id: "sk4", speaker: "Friend", narragansett: "Papóne", english: "Winter.", startSec: 4.5, endSec: 6 },
    ],
  }),

  // ——— Travel ———
  scene({
    id: "ask-path",
    title: "Show me the way",
    summary: "On the trail — asking directions with care.",
    chapter: "Travel",
    chapterNum: 11,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 70,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/ask-path.mp4",
    posterSrc: "/scenes/ask-path.jpg",
    durationSec: 8,
    tags: ["travel", "path"],
    lines: [
      { id: "p1", speaker: "Traveler", narragansett: "Nnatotemúckaun", english: "I will ask the way.", startSec: 0, endSec: 2 },
      { id: "p2", speaker: "Traveler", narragansett: "Kunnatótemous", english: "I will inquire of you.", startSec: 2, endSec: 3.8 },
      { id: "p3", speaker: "Traveler", narragansett: "Kokotemíinnea méyi", english: "Show me the way.", startSec: 3.8, endSec: 5.6 },
      { id: "p4", speaker: "Guide", narragansett: "Mishimmáyagat", english: "A great path.", startSec: 5.6, endSec: 7 },
      { id: "p5", speaker: "Guide", narragansett: "Peemáyagât", english: "A short way.", startSec: 7, endSec: 8 },
    ],
  }),

  // ——— Heavenly lights ———
  scene({
    id: "sky-moon",
    title: "Moon and stars",
    summary: "Heavenly lights — sun, moon, stars over the coast.",
    chapter: "The Heavenly Lights",
    chapterNum: 12,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 75,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/sky-moon.mp4",
    posterSrc: "/scenes/sky-moon.jpg",
    durationSec: 6,
    tags: ["moon", "stars", "sky"],
    lines: [
      {
        id: "sm1",
        speaker: "Speaker",
        narragansett: "Nippâwus",
        english: "The sun.",
        startSec: 0,
        endSec: 1.2,
        wordId: "rw-12-nipp-wus",
      },
      {
        id: "sm2",
        speaker: "Speaker",
        narragansett: "Nanepaùshat",
        english: "The moon.",
        startSec: 1.2,
        endSec: 2.5,
        wordId: "rw-12-nanepa-shat-and",
      },
      {
        id: "sm3",
        speaker: "Speaker",
        narragansett: "Yò Ockquitteunk",
        english: "A new moon.",
        startSec: 2.5,
        endSec: 3.7,
        wordId: "rw-12-y-ockquitteunk",
      },
      {
        id: "sm4",
        speaker: "Speaker",
        narragansett: "Anóckqus, anócksuck",
        english: "A star, stars.",
        startSec: 3.7,
        endSec: 5,
        wordId: "rw-12-an-ckqus-an-cksuck",
      },
      {
        id: "sm5",
        speaker: "Speaker",
        narragansett: "Mishánnock",
        english: "The morning star.",
        startSec: 5,
        endSec: 6,
        wordId: "rw-12-mish-nnock",
      },
    ],
  }),

  // ——— Weather ———
  scene({
    id: "weather-sky",
    title: "Reading the weather",
    summary: "Looking up — fair, cold, hot, and the wind.",
    chapter: "The Weather",
    chapterNum: 13,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 80,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/weather-sky.mp4",
    posterSrc: "/scenes/weather-sky.jpg",
    durationSec: 8,
    tags: ["weather", "sky"],
    lines: [
      { id: "w1", speaker: "Speaker", narragansett: "T Ocke tussinnámmin kéesuck", english: "What do you think of the weather?", startSec: 0, endSec: 2.2 },
      { id: "w2", speaker: "Speaker", narragansett: "Wekineaûquat", english: "Fair weather.", startSec: 2.2, endSec: 3.8 },
      { id: "w3", speaker: "Speaker", narragansett: "Tahkì or tátakki", english: "Cold weather.", startSec: 3.8, endSec: 5.4 },
      { id: "w4", speaker: "Speaker", narragansett: "Kussúttah", english: "It is hot.", startSec: 5.4, endSec: 6.6 },
      { id: "w5", speaker: "Speaker", narragansett: "W Aûpi", english: "The wind.", startSec: 6.6, endSec: 8 },
    ],
  }),

  // ——— Winds ———
  scene({
    id: "wind-rise",
    title: "Reading the winds",
    summary: "Wind names and waiting for a fair breeze.",
    chapter: "The Winds",
    chapterNum: 14,
    domain: "weather",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 85,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/wind-rise.mp4",
    posterSrc: "/scenes/wind-rise.jpg",
    durationSec: 6,
    tags: ["wind", "weather"],
    lines: [
      {
        id: "wr1",
        speaker: "Speaker",
        narragansett: "W Aûpi",
        english: "The wind.",
        startSec: 0,
        endSec: 1.1,
        wordId: "rw-14-w-a-pi",
      },
      {
        id: "wr2",
        speaker: "Speaker",
        narragansett: "Tashínash waupanash",
        english: "How many winds are there?",
        startSec: 1.1,
        endSec: 2.5,
        wordId: "rw-14-tash-nash-waupanash",
      },
      {
        id: "wr3",
        speaker: "Speaker",
        narragansett: "Nanúmmatin",
        english: "The north wind.",
        startSec: 2.5,
        endSec: 3.7,
        wordId: "rw-14-nan-mmatin",
      },
      {
        id: "wr4",
        speaker: "Speaker",
        narragansett: "Touwúttin",
        english: "South wind.",
        startSec: 3.7,
        endSec: 4.8,
        wordId: "rw-14-touw-ttin",
      },
      {
        id: "wr5",
        speaker: "Speaker",
        narragansett: "Nqénowhick wouttín",
        english: "I stay for a wind.",
        startSec: 4.8,
        endSec: 6,
        wordId: "rw-14-nq-nowhick-woutt-n",
      },
    ],
  }),

  // ——— Fowl ———
  scene({
    id: "birds-marsh",
    title: "Birds of the marsh",
    summary: "Fowl of the land and water — turkey, goose, blackbird, wing.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 90,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/birds-marsh.mp4",
    posterSrc: "/scenes/birds-marsh.jpg",
    durationSec: 6,
    tags: ["birds", "fowl", "marsh"],
    lines: [
      {
        id: "bm1",
        speaker: "Speaker",
        narragansett: "Néyhom, mâuog",
        english: "Turkey, turkeys.",
        startSec: 0,
        endSec: 1.4,
        wordId: "rw-15-n-yhom-m-uog",
      },
      {
        id: "bm2",
        speaker: "Speaker",
        narragansett: "Hònck, hònckock",
        english: "Goose, geese.",
        startSec: 1.4,
        endSec: 2.8,
        wordId: "rw-15-h-nck-h-nckock",
      },
      {
        id: "bm3",
        speaker: "Speaker",
        narragansett: "Chógan èuck",
        english: "Blackbird, blackbirds.",
        startSec: 2.8,
        endSec: 4.2,
        wordId: "rw-15-ch-gan-uck",
      },
      {
        id: "bm4",
        speaker: "Speaker",
        narragansett: "Wunnùp, pash",
        english: "Wing, wings.",
        startSec: 4.2,
        endSec: 5.2,
        wordId: "rw-15-wunn-p-pash",
      },
      {
        id: "bm5",
        speaker: "Speaker",
        narragansett: "Paupock, sûog",
        english: "Partridge, partridges.",
        startSec: 5.2,
        endSec: 6,
        wordId: "rw-15-paupock-s-og",
      },
    ],
  }),
  scene({
    id: "birds-kids",
    title: "Bird friends (kids)",
    summary: "Gentle cartoon birds for Little Ones — goose, turkey, blackbird.",
    chapter: "Fowl",
    chapterNum: 15,
    domain: "flora",
    sensitivity: "everyday",
    style: "cartoon",
    series: "Little Ones",
    pathOrder: 4,
    modesAllowed: ["little_ones", "young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/birds-kids.mp4",
    posterSrc: "/scenes/birds-kids.jpg",
    durationSec: 6,
    tags: ["kids", "birds", "cartoon"],
    lines: [
      { id: "bk1", speaker: "Friend", narragansett: "Hònck", english: "Goose.", startSec: 0, endSec: 2 },
      { id: "bk2", speaker: "Friend", narragansett: "Néyhom", english: "Turkey.", startSec: 2, endSec: 4 },
      { id: "bk3", speaker: "Friend", narragansett: "Chógan", english: "Blackbird.", startSec: 4, endSec: 6 },
    ],
  }),

  // ——— Earth & fruits ———
  scene({
    id: "earth-fruits",
    title: "Gifts of the earth",
    summary: "Land and corn — planting, seed-time, the living earth.",
    chapter: "Earth and Fruits",
    chapterNum: 16,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 95,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/earth-fruits.mp4",
    posterSrc: "/scenes/earth-fruits.jpg",
    durationSec: 6,
    tags: ["land", "plants", "corn"],
    lines: [
      {
        id: "e1",
        speaker: "Speaker",
        narragansett: "Aûke",
        english: "Earth or land.",
        startSec: 0,
        endSec: 1.2,
        wordId: "rw-16-a-ke-and",
      },
      {
        id: "e2",
        speaker: "Speaker",
        narragansett: "Ewáchim neash",
        english: "Corn.",
        startSec: 1.2,
        endSec: 2.4,
        wordId: "rw-16-ew-chim-neash",
      },
      {
        id: "e3",
        speaker: "Speaker",
        narragansett: "Scannémeneash",
        english: "Seed corn.",
        startSec: 2.4,
        endSec: 3.6,
        wordId: "rw-16-scann-meneash",
      },
      {
        id: "e4",
        speaker: "Speaker",
        narragansett: "Aukeeteaûmen",
        english: "To plant corn.",
        startSec: 3.6,
        endSec: 4.8,
        wordId: "rw-16-aukeetea-men",
      },
      {
        id: "e5",
        speaker: "Speaker",
        narragansett: "Aukeeteámitch",
        english: "Spring — seed-time.",
        startSec: 4.8,
        endSec: 6,
        wordId: "rw-10-aukeete-mitch",
      },
    ],
  }),

  // ——— Beasts ———
  scene({
    id: "forest-deer",
    title: "Deer in the forest",
    summary: "Beasts of the land — deer and otter of the woods and water.",
    chapter: "Beasts",
    chapterNum: 17,
    domain: "flora",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 100,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/forest-deer.mp4",
    posterSrc: "/scenes/forest-deer.jpg",
    durationSec: 6,
    tags: ["deer", "animals", "forest"],
    lines: [
      {
        id: "fd1",
        speaker: "Speaker",
        narragansett: "Attuck, quock",
        english: "Deer.",
        startSec: 0,
        endSec: 1.5,
        wordId: "rw-17-attuck-quock",
      },
      {
        id: "fd2",
        speaker: "Speaker",
        narragansett: "Wawwúnnes",
        english: "A young buck.",
        startSec: 1.5,
        endSec: 3,
        wordId: "rw-17-waww-nnes",
      },
      {
        id: "fd3",
        speaker: "Speaker",
        narragansett: "Kuttíomp",
        english: "A great buck.",
        startSec: 3,
        endSec: 4.5,
        wordId: "rw-17-kutt-omp-paucott-uwaw",
      },
      {
        id: "fd4",
        speaker: "Speaker",
        narragansett: "Nkéke, nkéquock",
        english: "Otter, otters.",
        startSec: 4.5,
        endSec: 6,
        wordId: "rw-17-nk-ke-nk-quock",
      },
    ],
  }),

  // ——— Sea ———
  scene({
    id: "canoe-shore",
    title: "At the shore",
    summary: "Canoe and water — the sea road in motion.",
    chapter: "The Sea",
    chapterNum: 18,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 105,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/canoe-shore.mp4",
    posterSrc: "/scenes/canoe-shore.jpg",
    durationSec: 8,
    tags: ["water", "canoe", "sea"],
    lines: [
      { id: "c1", speaker: "Paddler", narragansett: "Nickquénum", english: "I am going.", startSec: 0, endSec: 2 },
      { id: "c2", speaker: "Paddler", narragansett: "Acâwmuck nóteshem", english: "I came over the water.", startSec: 2, endSec: 4.2 },
      { id: "c3", speaker: "Paddler", narragansett: "Nippâwus", english: "The sun.", startSec: 4.2, endSec: 5.8 },
      { id: "c4", speaker: "Paddler", narragansett: "W Aûpi", english: "The wind.", startSec: 5.8, endSec: 8 },
    ],
  }),

  // ——— Fish ———
  scene({
    id: "fish-water",
    title: "Fish and fishing",
    summary: "Fishing vocabulary — fish, bass, going out to fish.",
    chapter: "Fish and Fishing",
    chapterNum: 19,
    domain: "water",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Sky & water",
    pathOrder: 110,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/fish-water.mp4",
    posterSrc: "/scenes/fish-water.jpg",
    durationSec: 6,
    tags: ["fish", "water", "shore"],
    lines: [
      {
        id: "f1",
        speaker: "Speaker",
        narragansett: "Namaùus,-suck",
        english: "Fish, fishes.",
        startSec: 0,
        endSec: 1.4,
        wordId: "rw-19-nama-us-suck",
      },
      {
        id: "f2",
        speaker: "Speaker",
        narragansett: "Ntaûmen",
        english: "I am fishing.",
        startSec: 1.4,
        endSec: 2.8,
        wordId: "rw-19-nta-men",
      },
      {
        id: "f3",
        speaker: "Speaker",
        narragansett: "Nnattuckqunnûwem",
        english: "I go a fishing.",
        startSec: 2.8,
        endSec: 4.2,
        wordId: "rw-19-nnattuckqunn-wem",
      },
      {
        id: "f4",
        speaker: "Speaker",
        narragansett: "Missúckeke-kéquock",
        english: "Bass.",
        startSec: 4.2,
        endSec: 5.2,
        wordId: "rw-19-miss-ckeke-k-quock",
      },
      {
        id: "f5",
        speaker: "Speaker",
        narragansett: "Aúmanep",
        english: "A fishing line.",
        startSec: 5.2,
        endSec: 6,
        wordId: "rw-19-a-manep",
      },
    ],
  }),

  // ——— Trade ———
  scene({
    id: "trade-shore",
    title: "Trade at the shore",
    summary: "Exchange and trust — market language with care.",
    chapter: "Buying and Selling",
    chapterNum: 25,
    domain: "tools",
    sensitivity: "careful",
    style: "cinematic",
    series: "Trade",
    pathOrder: 120,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/trade-shore.mp4",
    posterSrc: "/scenes/trade-shore.jpg",
    durationSec: 8,
    tags: ["trade", "wampum", "market"],
    lines: [
      { id: "t1", speaker: "Trader", narragansett: "Cowaúnckamish", english: "My respects to you.", startSec: 0, endSec: 1.8 },
      { id: "t2", speaker: "Trader", narragansett: "Téaquacumméich", english: "What will you have?", startSec: 1.8, endSec: 3.6 },
      { id: "t3", speaker: "Buyer", narragansett: "Taubút paump maúntaman", english: "I am glad (of this).", startSec: 3.6, endSec: 5.4 },
      { id: "t4", speaker: "Trader", narragansett: "Cummautaunchemókous", english: "I have finished my news.", startSec: 5.4, endSec: 7 },
      { id: "t5", speaker: "Both", narragansett: "Cowaúnckamish", english: "My respects to you.", startSec: 7, endSec: 8 },
    ],
  }),

  // ——— Hunting (language of the trail — no violence in video) ———
  scene({
    id: "hunt-trail",
    title: "On the hunt trail",
    summary:
      "Hunting language of going out and returning — respectful trail words (no violence shown).",
    chapter: "Hunting",
    chapterNum: 27,
    domain: "movement",
    sensitivity: "everyday",
    style: "cinematic",
    series: "Land & travel",
    pathOrder: 115,
    modesAllowed: ["young_learner", "core_adult", "elder"],
    videoSrc: "/scenes/hunt-trail.mp4",
    posterSrc: "/scenes/hunt-trail.jpg",
    durationSec: 6,
    tags: ["hunt", "trail", "forest"],
    lines: [
      {
        id: "ht1",
        speaker: "Speaker",
        narragansett: "Ntauchaûmen",
        english: "I go to hunt.",
        startSec: 0,
        endSec: 1.3,
        wordId: "rw-27-ntaucha-men",
      },
      {
        id: "ht2",
        speaker: "Speaker",
        narragansett: "Auchaûtuck",
        english: "Let us hunt.",
        startSec: 1.3,
        endSec: 2.5,
        wordId: "rw-27-aucha-tuck",
      },
      {
        id: "ht3",
        speaker: "Speaker",
        narragansett: "Nowetauchaûmen",
        english: "I will hunt with you.",
        startSec: 2.5,
        endSec: 3.8,
        wordId: "rw-27-nowetaucha-men",
      },
      {
        id: "ht4",
        speaker: "Speaker",
        narragansett: "Npunnowwâumen",
        english: "I must go to my traps.",
        startSec: 3.8,
        endSec: 5,
        wordId: "rw-27-npunnoww-umen",
      },
      {
        id: "ht5",
        speaker: "Speaker",
        narragansett: "Ntaumpauchaúmen",
        english: "I come from hunting.",
        startSec: 5,
        endSec: 6,
        wordId: "rw-27-ntaumpaucha-men",
      },
    ],
  }),

  // ——— Upload-ready scaffolds (sensitive / careful chapters — media later) ———
  scene({
    id: "wampum-count",
    title: "Shells of exchange",
    summary:
      "Coin and wampum scaffold — drop your own video when ready (Adult / Elder).",
    chapter: "Coin and Wampum",
    chapterNum: 24,
    domain: "tools",
    sensitivity: "careful",
    style: "cinematic",
    series: "Trade",
    pathOrder: 125,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/count-shells.mp4",
    posterSrc: "/scenes/count-shells.jpg",
    durationSec: 6,
    mediaStatus: "awaiting_upload",
    tags: ["wampum", "trade", "upload-ready"],
    reconstructionNote:
      "Dialogue scaffold ready. Upload public/scenes/uploads/wampum-count.mp4 when you have community footage. Stand-in uses counting shells clip.",
    lines: [
      {
        id: "wc1",
        speaker: "Speaker",
        narragansett: "Neesaúmscat",
        english: "Two pence (shell measure).",
        startSec: 0,
        endSec: 1.5,
        wordId: "rw-24-neesa-mscat",
      },
      {
        id: "wc2",
        speaker: "Speaker",
        narragansett: "Napannetashaúmscat",
        english: "Five pence.",
        startSec: 1.5,
        endSec: 3,
        wordId: "rw-24-napannetasha-mscat",
      },
      {
        id: "wc3",
        speaker: "Speaker",
        narragansett: "Piuckquaúmscat",
        english: "Ten pence.",
        startSec: 3,
        endSec: 4.5,
        wordId: "rw-24-piuckqua-mscat",
      },
      {
        id: "wc4",
        speaker: "Speaker",
        narragansett: "Neesaumpaúgatuck",
        english: "Two fathom.",
        startSec: 4.5,
        endSec: 6,
        wordId: "rw-24-neesaumpa-gatuck",
      },
    ],
  }),
  scene({
    id: "clothing-words",
    title: "Clothing words",
    summary:
      "Clothing vocabulary scaffold (careful chapter) — upload community media when ready.",
    chapter: "Clothing",
    chapterNum: 20,
    domain: "tools",
    sensitivity: "careful",
    style: "cinematic",
    series: "Daily life",
    pathOrder: 130,
    modesAllowed: ["core_adult", "elder"],
    videoSrc: "/scenes/home-fire.mp4",
    posterSrc: "/scenes/home-fire.jpg",
    durationSec: 6,
    mediaStatus: "awaiting_upload",
    tags: ["clothing", "upload-ready"],
    reconstructionNote:
      "Careful historical chapter. Upload public/scenes/uploads/clothing-words.mp4 for community-approved visuals. Stand-in uses home-fire clip.",
    lines: [
      {
        id: "cw1",
        speaker: "Speaker",
        narragansett: "Mocússinass",
        english: "Shoes (moccasins).",
        startSec: 0,
        endSec: 2,
        wordId: "rw-20-moc-ssinass-mockussinchass",
      },
      {
        id: "cw2",
        speaker: "Speaker",
        narragansett: "Saunketíppo",
        english: "A hat or cap.",
        startSec: 2,
        endSec: 4,
      },
      {
        id: "cw3",
        speaker: "Speaker",
        narragansett: "Muckíis auhaqut",
        english: "A child's mantle.",
        startSec: 4,
        endSec: 6,
      },
    ],
  }),
];

export function getAllScenes(): LearningScene[] {
  return SCENES;
}
