"""Shared Adult Path line lists — sole source for rebuild + catalog.

Same Narragansett forms as Little Ones / Young Path; Friend Tan + Friend Teal as adults.
"""

from __future__ import annotations

# clip_id → list of (line_id, narragansett, english)
CLIPS: dict[str, list[tuple[str, str, str]]] = {
    "greeting-adult": [
        ("ga1", "Ascowequassunnúmmis", "Good morning."),
        ("ga2", "Askuttaaquompsín", "How are you?"),
        ("ga3", "Asnpaumpmaúntam", "I am very well."),
        ("ga4", "Cowaúnckamish", "My respects to you."),
        ("ga5", "Taubotneanawáyean", "I thank you."),
    ],
    "meal-adult": [
        ("ma1", "Niccàwkatone", "I am thirsty."),
        ("ma2", "Nip, or nipéwese", "Some water, please."),
        ("ma3", "Namitch, commetesímmin", "Stay — you must eat first."),
        ("ma4", "Téaquacumméich", "What will you eat?"),
        ("ma5", "Taubotneanawáyean", "I thank you."),
    ],
    "count-adult": [
        ("ca1", "Nquít", "One."),
        ("ca2", "Neèse", "Two."),
        ("ca3", "Nìsh", "Three."),
        ("ca4", "Yòh", "Four."),
        ("ca5", "Napánna", "Five."),
    ],
    "family-adult": [
        ("fa1", "Nósh", "My father."),
        ("fa2", "Okásu", "A mother."),
        ("fa3", "Nippápoos", "My child."),
        ("fa4", "Hômes", "An old man — an elder."),
        ("fa5", "Wénise", "An old woman — an elder."),
    ],
    "home-adult": [
        ("ha1", "Wetu", "A house, a dwelling."),
        ("ha2", "Wetuômuck", "At home."),
        ("ha3", "Wunnégin", "Welcome."),
        ("ha4", "Nkàtaquaum", "I am sleepy."),
        ("ha5", "Cowwêtuck", "Let us sleep."),
    ],
    "day-adult": [
        ("da1", "Páshisha", "It is sunrise."),
        ("da2", "Mautàbon", "It is day."),
        ("da3", "Nummáttaqúaw", "Morning, before noon."),
        ("da4", "Wayaàwi", "The sun is set."),
        ("da5", "Póppakunnetch", "Dark night."),
    ],
    "seasons-adult": [
        ("sa1", "Séquan", "Spring."),
        ("sa2", "Néepun", "Summer."),
        ("sa3", "Taquònck", "Fall, autumn."),
        ("sa4", "Papóne", "Winter."),
        ("sa5", "Aukeeteámitch", "Seed-time."),
    ],
    "birds-adult": [
        ("ba1", "Hònck", "Goose."),
        ("ba2", "Néyhom", "Turkey."),
        ("ba3", "Chógan", "Blackbird."),
        ("ba4", "Wunnùp", "Wing."),
        ("ba5", "Paupock", "Partridge."),
    ],
    "water-adult": [
        ("wa1", "Nip", "Water."),
        ("wa2", "Namaùus", "Fish."),
        ("wa3", "Ntaûmen", "I am fishing."),
        ("wa4", "Wunnágehan", "Fair wind."),
        ("wa5", "Nickquénum", "I am going."),
    ],
    "sleep-adult": [
        ("sla1", "Yo nickowémen?", "Shall I sleep here?"),
        ("sla2", "Wunnégin, cówish", "Welcome — sleep here."),
        ("sla3", "Nkàtaquaum", "I am sleepy."),
        ("sla4", "Cowwêtuck", "Let us sleep."),
        ("sla5", "Mattannauke", "Fine mats to sleep on."),
    ],
    "path-adult": [
        ("pa1", "Kokotemíinnea méyi", "Show me the way."),
        ("pa2", "Peemáyagât", "A short way."),
        ("pa3", "Mishimmáyagat", "A great path."),
        ("pa4", "Taubotneanawáyean", "I thank you."),
        ("pa5", "Nickquénum", "I am going."),
    ],
    "land-adult": [
        ("la1", "Aûke", "Earth or land."),
        ("la2", "Ewáchim neash", "Corn."),
        ("la3", "Scannémeneash", "Seed corn."),
        ("la4", "Aukeeteaûmen", "To plant corn."),
        ("la5", "Sókenug", "A heap of corn."),
    ],
}

# Student oral seed (same language) — normalize into adult slots
STUDENT_SEED: dict[str, str] = {
    "ga1": "gs1", "ga2": "gs2", "ga3": "gs3", "ga4": "gs4", "ga5": "gs5",
    "ma1": "ms1", "ma2": "ms2", "ma3": "ms3", "ma4": "ms4", "ma5": "ms5",
    "ca1": "cs1", "ca2": "cs2", "ca3": "cs3", "ca4": "cs4", "ca5": "cs5",
    "fa1": "fs1", "fa2": "fs2", "fa3": "fs3", "fa4": "fs4", "fa5": "fs5",
    "ha1": "hs1", "ha2": "hs2", "ha3": "hs3", "ha4": "hs4", "ha5": "hs5",
    "da1": "ds1", "da2": "ds2", "da3": "ds3", "da4": "ds4", "da5": "ds5",
    "sa1": "ss1", "sa2": "ss2", "sa3": "ss3", "sa4": "ss4", "sa5": "ss5",
    "ba1": "bs1", "ba2": "bs2", "ba3": "bs3", "ba4": "bs4", "ba5": "bs5",
    "wa1": "ws1", "wa2": "ws2", "wa3": "ws3", "wa4": "ws4", "wa5": "ws5",
    "sla1": "sls1", "sla2": "sls2", "sla3": "sls3", "sla4": "sls4", "sla5": "sls5",
    "pa1": "ps1", "pa2": "ps2", "pa3": "ps3", "pa4": "ps4", "pa5": "ps5",
    "la1": "ls1", "la2": "ls2", "la3": "ls3", "la4": "ls4", "la5": "ls5",
}

STUDENT_CLIP: dict[str, str] = {
    "greeting-adult": "greeting-student",
    "meal-adult": "meal-student",
    "count-adult": "count-student",
    "family-adult": "family-student",
    "home-adult": "home-student",
    "day-adult": "day-student",
    "seasons-adult": "seasons-student",
    "birds-adult": "birds-student",
    "water-adult": "water-student",
    "sleep-adult": "sleep-student",
    "path-adult": "path-student",
    "land-adult": "land-student",
}

CLIP_META: dict[str, dict] = {
    "greeting-adult": {
        "title": "Hello, friend",
        "summary": "Greetings with Friend Tan and Friend Teal as adults — Adult Path, cinematic speak-first.",
        "chapter": "Of salutation",
        "chapterNum": 1,
        "domain": "other",
        "pathOrder": 1,
        "tags": ["hq", "adult", "greeting", "cinematic", "speak", "adult-path"],
    },
    "meal-adult": {
        "title": "Share the bowl",
        "summary": "Food and welcome words with the same two friends as adults.",
        "chapter": "Of their eating",
        "chapterNum": 2,
        "domain": "food",
        "pathOrder": 2,
        "tags": ["hq", "adult", "food", "cinematic", "speak", "adult-path"],
    },
    "count-adult": {
        "title": "Count with me",
        "summary": "Count one to five — Adult Path cinematic speak-first.",
        "chapter": "Of their numbers",
        "chapterNum": 4,
        "domain": "time",
        "pathOrder": 3,
        "tags": ["hq", "adult", "numbers", "cinematic", "speak", "adult-path"],
    },
    "family-adult": {
        "title": "Family words",
        "summary": "Father, mother, child, elders — leads are Friend Tan and Friend Teal as adults.",
        "chapter": "Of the family",
        "chapterNum": 5,
        "domain": "kinship",
        "pathOrder": 4,
        "tags": ["hq", "adult", "family", "cinematic", "speak", "adult-path"],
    },
    "home-adult": {
        "title": "Home wetu",
        "summary": "Wetu home words with the adult cast — bark-mat dome locked.",
        "chapter": "Of the family and house",
        "chapterNum": 6,
        "domain": "kinship",
        "pathOrder": 5,
        "tags": ["hq", "adult", "home", "cinematic", "speak", "adult-path"],
    },
    "day-adult": {
        "title": "Day light",
        "summary": "Sunrise to night with Friend Tan and Friend Teal as adults.",
        "chapter": "Of the time of the day",
        "chapterNum": 9,
        "domain": "time",
        "pathOrder": 6,
        "tags": ["hq", "adult", "day", "cinematic", "speak", "adult-path"],
    },
    "seasons-adult": {
        "title": "Four seasons",
        "summary": "Spring through seed-time — Adult Path cinematic speak-first.",
        "chapter": "Of the seasons",
        "chapterNum": 10,
        "domain": "time",
        "pathOrder": 7,
        "tags": ["hq", "adult", "seasons", "cinematic", "speak", "adult-path"],
    },
    "birds-adult": {
        "title": "Bird friends",
        "summary": "Bird words with the same two friends as adults.",
        "chapter": "Fowl",
        "chapterNum": 15,
        "domain": "flora",
        "pathOrder": 8,
        "tags": ["hq", "adult", "birds", "cinematic", "speak", "adult-path"],
    },
    "water-adult": {
        "title": "By the water",
        "summary": "Shore and water words — Adult Path cinematic speak-first.",
        "chapter": "Of the sea",
        "chapterNum": 18,
        "domain": "water",
        "pathOrder": 9,
        "tags": ["hq", "adult", "water", "cinematic", "speak", "adult-path"],
    },
    "sleep-adult": {
        "title": "Night rest",
        "summary": "Sleep and lodging words with the adult cast.",
        "chapter": "Of sleep and lodging",
        "chapterNum": 3,
        "domain": "kinship",
        "pathOrder": 10,
        "tags": ["hq", "adult", "sleep", "cinematic", "speak", "adult-path"],
    },
    "path-adult": {
        "title": "On the path",
        "summary": "Travel and path words with Friend Tan and Friend Teal as adults.",
        "chapter": "Of travel",
        "chapterNum": 11,
        "domain": "movement",
        "pathOrder": 11,
        "tags": ["hq", "adult", "path", "cinematic", "speak", "adult-path"],
    },
    "land-adult": {
        "title": "Corn and land",
        "summary": "Earth and corn with the adult cast — Adult Path cinematic speak-first.",
        "chapter": "Of the earth and fruits",
        "chapterNum": 16,
        "domain": "flora",
        "pathOrder": 12,
        "tags": ["hq", "adult", "land", "cinematic", "speak", "adult-path"],
    },
}
