"""Shared Young Path (Student) line lists — sole source for rebuild + catalog."""

from __future__ import annotations

# clip_id → list of (line_id, narragansett, english)
CLIPS: dict[str, list[tuple[str, str, str]]] = {
    "greeting-student": [
        ("gs1", "Ascowequassunnúmmis", "Good morning."),
        ("gs2", "Askuttaaquompsín", "How are you?"),
        ("gs3", "Asnpaumpmaúntam", "I am very well."),
        ("gs4", "Cowaúnckamish", "My respects to you."),
        ("gs5", "Taubotneanawáyean", "I thank you."),
    ],
    "meal-student": [
        ("ms1", "Niccàwkatone", "I am thirsty."),
        ("ms2", "Nip, or nipéwese", "Some water, please."),
        ("ms3", "Namitch, commetesímmin", "Stay — you must eat first."),
        ("ms4", "Téaquacumméich", "What will you eat?"),
        ("ms5", "Taubotneanawáyean", "I thank you."),
    ],
    "count-student": [
        ("cs1", "Nquít", "One."),
        ("cs2", "Neèse", "Two."),
        ("cs3", "Nìsh", "Three."),
        ("cs4", "Yòh", "Four."),
        ("cs5", "Napánna", "Five."),
    ],
    "family-student": [
        ("fs1", "Nósh", "My father."),
        ("fs2", "Okásu", "A mother."),
        ("fs3", "Nippápoos", "My child."),
        ("fs4", "Hômes", "An old man — an elder."),
        ("fs5", "Wénise", "An old woman — an elder."),
    ],
    "home-student": [
        ("hs1", "Wetu", "A house, a dwelling."),
        ("hs2", "Wetuômuck", "At home."),
        ("hs3", "Wunnégin", "Welcome."),
        ("hs4", "Nkàtaquaum", "I am sleepy."),
        ("hs5", "Cowwêtuck", "Let us sleep."),
    ],
    "day-student": [
        ("ds1", "Páshisha", "It is sunrise."),
        ("ds2", "Mautàbon", "It is day."),
        ("ds3", "Nummáttaqúaw", "Morning, before noon."),
        ("ds4", "Wayaàwi", "The sun is set."),
        ("ds5", "Póppakunnetch", "Dark night."),
    ],
    "seasons-student": [
        ("ss1", "Séquan", "Spring."),
        ("ss2", "Néepun", "Summer."),
        ("ss3", "Taquònck", "Fall, autumn."),
        ("ss4", "Papóne", "Winter."),
        ("ss5", "Aukeeteámitch", "Seed-time."),
    ],
    "birds-student": [
        ("bs1", "Hònck", "Goose."),
        ("bs2", "Néyhom", "Turkey."),
        ("bs3", "Chógan", "Blackbird."),
        ("bs4", "Wunnùp", "Wing."),
        ("bs5", "Paupock", "Partridge."),
    ],
    "water-student": [
        ("ws1", "Nip", "Water."),
        ("ws2", "Namaùus", "Fish."),
        ("ws3", "Ntaûmen", "I am fishing."),
        ("ws4", "Wunnágehan", "Fair wind."),
        ("ws5", "Nickquénum", "I am going."),
    ],
    "sleep-student": [
        ("sls1", "Yo nickowémen?", "Shall I sleep here?"),
        ("sls2", "Wunnégin, cówish", "Welcome — sleep here."),
        ("sls3", "Nkàtaquaum", "I am sleepy."),
        ("sls4", "Cowwêtuck", "Let us sleep."),
        ("sls5", "Mattannauke", "Fine mats to sleep on."),
    ],
    "path-student": [
        ("ps1", "Kokotemíinnea méyi", "Show me the way."),
        ("ps2", "Peemáyagât", "A short way."),
        ("ps3", "Mishimmáyagat", "A great path."),
        ("ps4", "Taubotneanawáyean", "I thank you."),
        ("ps5", "Nickquénum", "I am going."),
    ],
    "land-student": [
        ("ls1", "Aûke", "Earth or land."),
        ("ls2", "Ewáchim neash", "Corn."),
        ("ls3", "Scannémeneash", "Seed corn."),
        ("ls4", "Aukeeteaûmen", "To plant corn."),
        ("ls5", "Sókenug", "A heap of corn."),
    ],
}

# Parallel kids clip id (for still age-up seed paths)
KIDS_SEED: dict[str, str] = {
    "greeting-student": "greeting-kids",
    "meal-student": "meal-kids",
    "count-student": "count-kids",
    "family-student": "family-kids",
    "home-student": "home-kids",
    "day-student": "day-kids",
    "seasons-student": "seasons-kids",
    "birds-student": "birds-kids",
    "water-student": "water-kids",
    "sleep-student": "sleep-kids",
    "path-student": "path-kids",
    "land-student": "land-kids",
}

CLIP_META: dict[str, dict] = {
    "greeting-student": {
        "title": "Hello, friend",
        "summary": "Greetings with Friend Tan and Friend Teal as teens — Young Path, cinematic speak-first.",
        "chapter": "Of salutation",
        "chapterNum": 1,
        "domain": "other",
        "pathOrder": 1,
        "tags": ["hq", "student", "greeting", "cinematic", "speak", "young-path"],
    },
    "meal-student": {
        "title": "Share the bowl",
        "summary": "Food and welcome words with the same two friends, now teens.",
        "chapter": "Of their eating",
        "chapterNum": 2,
        "domain": "food",
        "pathOrder": 2,
        "tags": ["hq", "student", "food", "cinematic", "speak", "young-path"],
    },
    "count-student": {
        "title": "Count with me",
        "summary": "Count one to five — Young Path cinematic speak-first.",
        "chapter": "Of their numbers",
        "chapterNum": 4,
        "domain": "time",
        "pathOrder": 3,
        "tags": ["hq", "student", "numbers", "cinematic", "speak", "young-path"],
    },
    "family-student": {
        "title": "Family words",
        "summary": "Father, mother, child, elders — leads are Friend Tan and Friend Teal as teens.",
        "chapter": "Of the family",
        "chapterNum": 5,
        "domain": "kinship",
        "pathOrder": 4,
        "tags": ["hq", "student", "family", "cinematic", "speak", "young-path"],
    },
    "home-student": {
        "title": "Home wetu",
        "summary": "Wetu home words with the teen cast — bark-mat dome locked.",
        "chapter": "Of the family and house",
        "chapterNum": 6,
        "domain": "kinship",
        "pathOrder": 5,
        "tags": ["hq", "student", "home", "cinematic", "speak", "young-path"],
    },
    "day-student": {
        "title": "Day light",
        "summary": "Sunrise to night with Friend Tan and Friend Teal as teens.",
        "chapter": "Of the time of the day",
        "chapterNum": 9,
        "domain": "time",
        "pathOrder": 6,
        "tags": ["hq", "student", "day", "cinematic", "speak", "young-path"],
    },
    "seasons-student": {
        "title": "Four seasons",
        "summary": "Spring through seed-time — Young Path cinematic speak-first.",
        "chapter": "Of the seasons",
        "chapterNum": 10,
        "domain": "time",
        "pathOrder": 7,
        "tags": ["hq", "student", "seasons", "cinematic", "speak", "young-path"],
    },
    "birds-student": {
        "title": "Bird friends",
        "summary": "Bird words with the same two friends as teens.",
        "chapter": "Fowl",
        "chapterNum": 15,
        "domain": "flora",
        "pathOrder": 8,
        "tags": ["hq", "student", "birds", "cinematic", "speak", "young-path"],
    },
    "water-student": {
        "title": "By the water",
        "summary": "Shore and water words — Young Path cinematic speak-first.",
        "chapter": "Of the sea",
        "chapterNum": 18,
        "domain": "water",
        "pathOrder": 9,
        "tags": ["hq", "student", "water", "cinematic", "speak", "young-path"],
    },
    "sleep-student": {
        "title": "Night rest",
        "summary": "Sleep and lodging words with the teen cast.",
        "chapter": "Of sleep and lodging",
        "chapterNum": 3,
        "domain": "kinship",
        "pathOrder": 10,
        "tags": ["hq", "student", "sleep", "cinematic", "speak", "young-path"],
    },
    "path-student": {
        "title": "On the path",
        "summary": "Travel and path words with Friend Tan and Friend Teal as teens.",
        "chapter": "Of travel",
        "chapterNum": 11,
        "domain": "movement",
        "pathOrder": 11,
        "tags": ["hq", "student", "path", "cinematic", "speak", "young-path"],
    },
    "land-student": {
        "title": "Corn and land",
        "summary": "Earth and corn with the teen cast — Young Path cinematic speak-first.",
        "chapter": "Of the earth and fruits",
        "chapterNum": 16,
        "domain": "flora",
        "pathOrder": 12,
        "tags": ["hq", "student", "land", "cinematic", "speak", "young-path"],
    },
}
