/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDayRouteImport } from './routes/app/day'
import { Route as AppGuideRouteImport } from './routes/app/guide'
import { Route as AppKeyRouteImport } from './routes/app/key'
import { Route as AppListenRouteImport } from './routes/app/listen'
import { Route as AppPathsRouteImport } from './routes/app/paths'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppScenesRouteImport } from './routes/app/scenes'
import { Route as AppWordsRouteImport } from './routes/app/words'
import { Route as AppDayIndexRouteImport } from './routes/app/day.index'
import { Route as AppDayActIdRouteImport } from './routes/app/day.$actId'
import { Route as AppPathsIndexRouteImport } from './routes/app/paths.index'
import { Route as AppPathsIdRouteImport } from './routes/app/paths.$id'
import { Route as AppScenesIndexRouteImport } from './routes/app/scenes.index'
import { Route as AppScenesIdRouteImport } from './routes/app/scenes.$id'
import { Route as AppWordsIndexRouteImport } from './routes/app/words.index'
import { Route as AppWordsIdRouteImport } from './routes/app/words.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDayRoute = AppDayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppKeyRoute = AppKeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => AppRoute,
} as any)
const AppListenRoute = AppListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppScenesRoute = AppScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsRoute = AppWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AppRoute,
} as any)
const AppDayIndexRoute = AppDayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDayRoute,
} as any)
const AppDayActIdRoute = AppDayActIdRouteImport.update({
  id: '/$actId',
  path: '/$actId',
  getParentRoute: () => AppDayRoute,
} as any)
const AppPathsIndexRoute = AppPathsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPathsRoute,
} as any)
const AppPathsIdRoute = AppPathsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPathsRoute,
} as any)
const AppScenesIndexRoute = AppScenesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScenesRoute,
} as any)
const AppScenesIdRoute = AppScenesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppScenesRoute,
} as any)
const AppWordsIndexRoute = AppWordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWordsRoute,
} as any)
const AppWordsIdRoute = AppWordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/day': typeof AppDayRouteWithChildren
  '/app/guide': typeof AppGuideRoute
  '/app/key': typeof AppKeyRoute
  '/app/listen': typeof AppListenRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/scenes': typeof AppScenesRouteWithChildren
  '/app/words': typeof AppWordsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/day/$actId': typeof AppDayActIdRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/scenes/$id': typeof AppScenesIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/day/': typeof AppDayIndexRoute
  '/app/paths/': typeof AppPathsIndexRoute
  '/app/scenes/': typeof AppScenesIndexRoute
  '/app/words/': typeof AppWordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/key': typeof AppKeyRoute
  '/app/listen': typeof AppListenRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/day/$actId': typeof AppDayActIdRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/scenes/$id': typeof AppScenesIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/day': typeof AppDayIndexRoute
  '/app/paths': typeof AppPathsIndexRoute
  '/app/scenes': typeof AppScenesIndexRoute
  '/app/words': typeof AppWordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/day': typeof AppDayRouteWithChildren
  '/app/guide': typeof AppGuideRoute
  '/app/key': typeof AppKeyRoute
  '/app/listen': typeof AppListenRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/scenes': typeof AppScenesRouteWithChildren
  '/app/words': typeof AppWordsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/day/$actId': typeof AppDayActIdRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/scenes/$id': typeof AppScenesIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/day/': typeof AppDayIndexRoute
  '/app/paths/': typeof AppPathsIndexRoute
  '/app/scenes/': typeof AppScenesIndexRoute
  '/app/words/': typeof AppWordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/welcome'
    | '/api/tts'
    | '/app/day'
    | '/app/guide'
    | '/app/key'
    | '/app/listen'
    | '/app/paths'
    | '/app/profile'
    | '/app/scenes'
    | '/app/words'
    | '/app/'
    | '/app/day/$actId'
    | '/app/paths/$id'
    | '/app/scenes/$id'
    | '/app/words/$id'
    | '/app/day/'
    | '/app/paths/'
    | '/app/scenes/'
    | '/app/words/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/api/tts'
    | '/app/guide'
    | '/app/key'
    | '/app/listen'
    | '/app/profile'
    | '/app'
    | '/app/day/$actId'
    | '/app/paths/$id'
    | '/app/scenes/$id'
    | '/app/words/$id'
    | '/app/day'
    | '/app/paths'
    | '/app/scenes'
    | '/app/words'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/welcome'
    | '/api/tts'
    | '/app/day'
    | '/app/guide'
    | '/app/key'
    | '/app/listen'
    | '/app/paths'
    | '/app/profile'
    | '/app/scenes'
    | '/app/words'
    | '/app/'
    | '/app/day/$actId'
    | '/app/paths/$id'
    | '/app/scenes/$id'
    | '/app/words/$id'
    | '/app/day/'
    | '/app/paths/'
    | '/app/scenes/'
    | '/app/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/day': {
      id: '/app/day'
      path: '/day'
      fullPath: '/app/day'
      preLoaderRoute: typeof AppDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/key': {
      id: '/app/key'
      path: '/key'
      fullPath: '/app/key'
      preLoaderRoute: typeof AppKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/listen': {
      id: '/app/listen'
      path: '/listen'
      fullPath: '/app/listen'
      preLoaderRoute: typeof AppListenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths': {
      id: '/app/paths'
      path: '/paths'
      fullPath: '/app/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenes': {
      id: '/app/scenes'
      path: '/scenes'
      fullPath: '/app/scenes'
      preLoaderRoute: typeof AppScenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/words': {
      id: '/app/words'
      path: '/words'
      fullPath: '/app/words'
      preLoaderRoute: typeof AppWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/day/': {
      id: '/app/day/'
      path: '/'
      fullPath: '/app/day/'
      preLoaderRoute: typeof AppDayIndexRouteImport
      parentRoute: typeof AppDayRoute
    }
    '/app/day/$actId': {
      id: '/app/day/$actId'
      path: '/$actId'
      fullPath: '/app/day/$actId'
      preLoaderRoute: typeof AppDayActIdRouteImport
      parentRoute: typeof AppDayRoute
    }
    '/app/paths/': {
      id: '/app/paths/'
      path: '/'
      fullPath: '/app/paths/'
      preLoaderRoute: typeof AppPathsIndexRouteImport
      parentRoute: typeof AppPathsRoute
    }
    '/app/paths/$id': {
      id: '/app/paths/$id'
      path: '/$id'
      fullPath: '/app/paths/$id'
      preLoaderRoute: typeof AppPathsIdRouteImport
      parentRoute: typeof AppPathsRoute
    }
    '/app/scenes/': {
      id: '/app/scenes/'
      path: '/'
      fullPath: '/app/scenes/'
      preLoaderRoute: typeof AppScenesIndexRouteImport
      parentRoute: typeof AppScenesRoute
    }
    '/app/scenes/$id': {
      id: '/app/scenes/$id'
      path: '/$id'
      fullPath: '/app/scenes/$id'
      preLoaderRoute: typeof AppScenesIdRouteImport
      parentRoute: typeof AppScenesRoute
    }
    '/app/words/': {
      id: '/app/words/'
      path: '/'
      fullPath: '/app/words/'
      preLoaderRoute: typeof AppWordsIndexRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/app/words/$id': {
      id: '/app/words/$id'
      path: '/$id'
      fullPath: '/app/words/$id'
      preLoaderRoute: typeof AppWordsIdRouteImport
      parentRoute: typeof AppWordsRoute
    }
  }
}

interface AppDayRouteChildren {
  AppDayActIdRoute: typeof AppDayActIdRoute
  AppDayIndexRoute: typeof AppDayIndexRoute
}

const AppDayRouteChildren: AppDayRouteChildren = {
  AppDayActIdRoute: AppDayActIdRoute,
  AppDayIndexRoute: AppDayIndexRoute,
}

const AppDayRouteWithChildren =
  AppDayRoute._addFileChildren(AppDayRouteChildren)

interface AppPathsRouteChildren {
  AppPathsIdRoute: typeof AppPathsIdRoute
  AppPathsIndexRoute: typeof AppPathsIndexRoute
}

const AppPathsRouteChildren: AppPathsRouteChildren = {
  AppPathsIdRoute: AppPathsIdRoute,
  AppPathsIndexRoute: AppPathsIndexRoute,
}

const AppPathsRouteWithChildren = AppPathsRoute._addFileChildren(
  AppPathsRouteChildren,
)

interface AppScenesRouteChildren {
  AppScenesIdRoute: typeof AppScenesIdRoute
  AppScenesIndexRoute: typeof AppScenesIndexRoute
}

const AppScenesRouteChildren: AppScenesRouteChildren = {
  AppScenesIdRoute: AppScenesIdRoute,
  AppScenesIndexRoute: AppScenesIndexRoute,
}

const AppScenesRouteWithChildren = AppScenesRoute._addFileChildren(
  AppScenesRouteChildren,
)

interface AppWordsRouteChildren {
  AppWordsIdRoute: typeof AppWordsIdRoute
  AppWordsIndexRoute: typeof AppWordsIndexRoute
}

const AppWordsRouteChildren: AppWordsRouteChildren = {
  AppWordsIdRoute: AppWordsIdRoute,
  AppWordsIndexRoute: AppWordsIndexRoute,
}

const AppWordsRouteWithChildren = AppWordsRoute._addFileChildren(
  AppWordsRouteChildren,
)

interface AppRouteChildren {
  AppDayRoute: typeof AppDayRouteWithChildren
  AppGuideRoute: typeof AppGuideRoute
  AppKeyRoute: typeof AppKeyRoute
  AppListenRoute: typeof AppListenRoute
  AppPathsRoute: typeof AppPathsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppScenesRoute: typeof AppScenesRouteWithChildren
  AppWordsRoute: typeof AppWordsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDayRoute: AppDayRouteWithChildren,
  AppGuideRoute: AppGuideRoute,
  AppKeyRoute: AppKeyRoute,
  AppListenRoute: AppListenRoute,
  AppPathsRoute: AppPathsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppScenesRoute: AppScenesRouteWithChildren,
  AppWordsRoute: AppWordsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
