/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppListenRouteImport } from './routes/app/listen'
import { Route as AppPathsRouteImport } from './routes/app/paths'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppWordsRouteImport } from './routes/app/words'
import { Route as AppPathsIndexRouteImport } from './routes/app/paths.index'
import { Route as AppPathsIdRouteImport } from './routes/app/paths.$id'
import { Route as AppWordsIndexRouteImport } from './routes/app/words.index'
import { Route as AppWordsIdRouteImport } from './routes/app/words.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppListenRoute = AppListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsRoute = AppWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsIndexRoute = AppPathsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPathsRoute,
} as any)
const AppPathsIdRoute = AppPathsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPathsRoute,
} as any)
const AppWordsIndexRoute = AppWordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWordsRoute,
} as any)
const AppWordsIdRoute = AppWordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/listen': typeof AppListenRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/words': typeof AppWordsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/paths/': typeof AppPathsIndexRoute
  '/app/words/': typeof AppWordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/listen': typeof AppListenRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/paths': typeof AppPathsIndexRoute
  '/app/words': typeof AppWordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/api/tts': typeof ApiTtsRoute
  '/app/listen': typeof AppListenRoute
  '/app/paths': typeof AppPathsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/words': typeof AppWordsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/paths/$id': typeof AppPathsIdRoute
  '/app/words/$id': typeof AppWordsIdRoute
  '/app/paths/': typeof AppPathsIndexRoute
  '/app/words/': typeof AppWordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/welcome'
    | '/api/tts'
    | '/app/listen'
    | '/app/paths'
    | '/app/profile'
    | '/app/words'
    | '/app/'
    | '/app/paths/$id'
    | '/app/words/$id'
    | '/app/paths/'
    | '/app/words/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/api/tts'
    | '/app/listen'
    | '/app/profile'
    | '/app'
    | '/app/paths/$id'
    | '/app/words/$id'
    | '/app/paths'
    | '/app/words'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/welcome'
    | '/api/tts'
    | '/app/listen'
    | '/app/paths'
    | '/app/profile'
    | '/app/words'
    | '/app/'
    | '/app/paths/$id'
    | '/app/words/$id'
    | '/app/paths/'
    | '/app/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/listen': {
      id: '/app/listen'
      path: '/listen'
      fullPath: '/app/listen'
      preLoaderRoute: typeof AppListenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths': {
      id: '/app/paths'
      path: '/paths'
      fullPath: '/app/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/words': {
      id: '/app/words'
      path: '/words'
      fullPath: '/app/words'
      preLoaderRoute: typeof AppWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths/': {
      id: '/app/paths/'
      path: '/'
      fullPath: '/app/paths/'
      preLoaderRoute: typeof AppPathsIndexRouteImport
      parentRoute: typeof AppPathsRoute
    }
    '/app/paths/$id': {
      id: '/app/paths/$id'
      path: '/$id'
      fullPath: '/app/paths/$id'
      preLoaderRoute: typeof AppPathsIdRouteImport
      parentRoute: typeof AppPathsRoute
    }
    '/app/words/': {
      id: '/app/words/'
      path: '/'
      fullPath: '/app/words/'
      preLoaderRoute: typeof AppWordsIndexRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/app/words/$id': {
      id: '/app/words/$id'
      path: '/$id'
      fullPath: '/app/words/$id'
      preLoaderRoute: typeof AppWordsIdRouteImport
      parentRoute: typeof AppWordsRoute
    }
  }
}

interface AppPathsRouteChildren {
  AppPathsIdRoute: typeof AppPathsIdRoute
  AppPathsIndexRoute: typeof AppPathsIndexRoute
}

const AppPathsRouteChildren: AppPathsRouteChildren = {
  AppPathsIdRoute: AppPathsIdRoute,
  AppPathsIndexRoute: AppPathsIndexRoute,
}

const AppPathsRouteWithChildren = AppPathsRoute._addFileChildren(
  AppPathsRouteChildren,
)

interface AppWordsRouteChildren {
  AppWordsIdRoute: typeof AppWordsIdRoute
  AppWordsIndexRoute: typeof AppWordsIndexRoute
}

const AppWordsRouteChildren: AppWordsRouteChildren = {
  AppWordsIdRoute: AppWordsIdRoute,
  AppWordsIndexRoute: AppWordsIndexRoute,
}

const AppWordsRouteWithChildren = AppWordsRoute._addFileChildren(
  AppWordsRouteChildren,
)

interface AppRouteChildren {
  AppListenRoute: typeof AppListenRoute
  AppPathsRoute: typeof AppPathsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppWordsRoute: typeof AppWordsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppListenRoute: AppListenRoute,
  AppPathsRoute: AppPathsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppWordsRoute: AppWordsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
